### ISSUE TITLE
Do not send "I am a helpful assistant! How can I help?" message to server

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#103]
It doesn't improve results to have that, costs us credits and token limit. I would replace it with a stand-in-message that disappears first time we click send.

**Comment by humphd** [comment]
What do you think about us adding a new message type: `ChatCraftAppMessage`.  These would show the ChatCraft icon for the Avatar and use `ChatCraft` as the name.  When we save messages to the db, or send to AI, we'd filter them out.  They would be app-only, informational messages.

We could probably use them to finish what I started in #66 and to show error messages, provide help messages, etc

<img width="966" alt="Screenshot 2023-06-13 at 4 20 47 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/956ab186-1101-4537-8f29-5100911d536c">

**Comment by tarasglek** [comment]
love it
