### ISSUE TITLE
Add support for wizardcoder

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#120]
https://github.com/nlpxucan/WizardLM/blob/main/WizardCoder/README.md

It's a fully open model that can be run locally. Should figure out some instructions for Macs and linux to expose a local model to chatcraft.

**Comment by tarasglek** [comment]
https://github.com/serge-chat/serge/ this is a good package that does the hard work of supporting all the models...on cpu though :(

**Comment by tarasglek** [comment]
Gpu api https://medium.com/@anchen.li/build-your-own-copliot-using-open-source-llm-ff9da556cb09

**Comment by humphd** [comment]
I think our support for custom providers is where we want to be for supporting stuff like this.
