### ISSUE TITLE
Decide if System Prompts should be included in search results

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#129]
<img width="1088" alt="Screenshot 2023-06-22 at 9 08 04 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/70b19dfa-cf7d-414e-b702-c2a31eab8b0c">

Previously, we didn't store the System Prompt Message in the chat's message list--we only added it when necessary to send to OpenAI.

However, now we are including it by default in all chats as a combination greeting and editable system prompt.

This means that you're going to start seeing a ton of duplication in searches when any word matches something in the system prompt text.

My question is: should I exclude all system prompts from search results?  The upside of this is that it will mean we don't ever have these duplicates of messages you don't care about.  The downside is that if you DO want to search for something in a custom system prompt, you won't be able to.

How should we handle this?

**Comment by tarasglek** [comment]
That's tough. Almost worth adding a filter toggle to search...but also excluding seems ok for now.
