### ISSUE TITLE
Better storage for messages

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#13]
Currently, the messages are stored as an `Array` in `localStorage`.  This is OK, but it has limits, since we can't store more than 5M.  If we want to store everything we ever do, search it, etc. we could improve things by moving to `indexeddb`.

We could consider using a lib like [dexie](https://dexie.org/docs/Tutorial/React), which has interesting hooks to do live queries like this:

```ts
const messages = useLiveQuery(
    async () => {
      //
      // Query Dexie's API
      //
      const mesages = await db.messages
        .where('some search criteria...')
        .toArray();

      // Return result
      return messages;
    },
  );
```

Using this, we could create separate threads vs. only have the current chat session, give the ability to search across those threads, pick up where we left off in a past conversation, etc.

There might be something better than `dexie`, it's just one option I know of that supports React well (I haven't used it before).

**Comment by tarasglek** [comment]
Note this ties in with indexing via https://twitter.com/nfcampos/status/1651915458222718976

**Comment by humphd** [comment]
Let's figure out what we actually want to store.  Things I'm considering:

1. Chats (i.e., lists of Messages like we have now), but augmented with date info (e.g., each chat has a date when it was created and each message has date info).  Having dates (or some other unique id) will make it easier in UI to use as a `key` or React
2. Documents.  Could be hunks of code you paste in, files you upload.  I'm imagining being able to drag one or more files into the app and have them get used as part of the chat somehow
3. Embeddings.  For both 1. and 2., it would be useful to create and store embeddings so we can do semantic search later on for building context
4. Settings.  I think what we do now with `localStorage` is fine for this.

It probably makes sense to use IndexedDB for this, since it gives us lots of room.  However, langchainjs also has this notion of a [Vector Store](https://js.langchain.com/docs/modules/indexes/vector_stores/), which combines document + embedding storage and retrieval/querying.  Most of the [ones they support](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/) are cloud-based, but we could start with [MemoryVectorStore](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/memory), and if it works, write an IndexedDBVectorStore based on [their code](https://github.com/hwchase17/langchainjs/blob/2886ad92d97c1f9efdfbc1906d61e57265b16b5a/langchain/src/vectorstores/memory.ts).

For the Chat Messages, we can probably use a [MarkdownTextSplitter](https://js.langchain.com/docs/modules/indexes/text_splitters/examples/markdown) to extract documents, or just use them messages whole.

For embeddings, we can use the [TensorFlowEmbeddings](https://js.langchain.com/docs/modules/models/embeddings/integrations#tensorflowembeddings) in browser.

So given all of the above, what does our DB look like?  Dexie and other IndexedDB-based libs require a table layout, so we could do something like:

```ts
interface Message {
  id?: number // auto-increment
  created: Date;
  type: 'ai' | 'human' | 'system';
  content: string;
}

interface Chat {
  id?: number; // auto-increment
  created: Date;
  messageIds: number[]; // store IDs for messages in the chat, in order
}
```

And then the code to get all messages for a given chat would look like:

```ts
// Get the chat we want to work with
const chat = await chats.get(chatId);

if (chat) {
  // Grab all the message IDs in this chat
  const messageIds = chat.messageIds;
  // Get all messages based on these IDs in an array
  const chatMessages = await messages.where('id').anyOf(messageIds).toArray();
}
```

**Comment by humphd** [comment]
IDB Vector Store - https://twitter.com/paul_kinlan/status/1655318811036246016?s=51&t=Q-jSo3oqjJCmqVa-pXrlSQ

This approach could be useful for what we want to do.

**Comment by humphd** [comment]
I've got a branch that implements the UI for this, with a responsive sidebar (default closed on mobile/small screens, default open on wider):

<img width="1233" alt="Screenshot 2023-05-27 at 9 42 07 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/da2e9a34-c8c1-47b6-8a54-4a9871e9edbc">
<img width="734" alt="Screenshot 2023-05-27 at 9 43 37 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/0ed9f0a1-9d01-404c-8f5c-ecd6133bc19c">

Implementing this has raised some questions though, and I'd appreciate some help thinking them through (@tarasglek, @steven4354, and whoever else is an active user);

1. Should **all** chats get saved to the local database, or only ones you explicitly specify?
    1. If YES, when should it happen?  Immediately when you start a new chat, or only at the end?  I ask because I need to put some kind of `title` in the sidebar (more on that below).
    2. If NO, what is the workflow for saving?  Do we have a `Save` button?  Do you have to click `Save` every time you add more messages to a chat, or does it auto-save thereafter? 
1. What do we put in the sidebar for the `title`?  Do we auto-summarize the chat for you (what ChatGPT does)?  If so, when do we do that, since the summary will change as you add more messages.  Do we use the first few words of the initial prompt (again, problematic when you haven't typed anything yet)?  Do we use the date until we have context?  Do we add UI to have users enter this manually (that feels like a lot of work)? Make it optional?

**Comment by tarasglek** [comment]
I don't have strong opinions on ui for this. 
1. We shouldn't have save buttons
2. need to think about how to handle chats where 'current' convo diverges in 2 diff tabs. I think easy solution is to mark current convo as draft with assumption that drafts are less persistent
3. once you do use a 'saved convo' to chat to..what do you do then with multiple windows..feels like you should be syncing it
4. should we have server-side convos too?
5. I find i never went to saved convos in chatgpt, so i'm not sure how much value that has over "shared" convos where you explicitly wanna share something

**Comment by humphd** [comment]
This is helpful, and it's helping me think this through.  Here's what I'm thinking:

1. No "save" buttons--everything is automatic
2. When you go to `chatcraft.org/` we create a new chat for you and redirect you to that URL `chatcraft.org/c/:uuid` invisibly, for example: http://localhost:5173/c/17482059-3751-427d-846c-c66cdc08bcbd
3. If you open http://localhost:5173/c/17482059-3751-427d-846c-c66cdc08bcbd in another tab, it's always in sync with any other tab that has that chat open
4. When you add a new message to a chat, we add it to the db
5. The sidebar shows you the public/shared/network chats vs. your private/offline chats.
6. Search looks for some string within the messages in all your messages, and the results show you the resulting messages (vs chats).  So we can show more context in the sidebar (e.g., 2 lines of text with some surrounding context).
7. We don't bother with title/summary for the local stuff, but offer ways to set it for public ones (manual, automatic, or AI generated)
8. Include "fork" button (not sure if this is the right word, but maybe for our audience) for a chat, so you can start a new one that diverges from current.  So if I'm in chat http://localhost:5173/c/17482059-3751-427d-846c-c66cdc08bcbd, I can click "Fork" and get a totally new one, with same messages, but different URL.  New messages added to either thread stay as part of that thread.

Do "shared" chats (R2) serve the needs of "server-side convos" or is that something else?

**Comment by tarasglek** [comment]
all sounds good, but i'm confused on "server-side chats" where did that come from?

**Comment by humphd** [comment]
> 5\. should we have server-side convos too?

I was including because [you mentioned it above](https://github.com/tarasglek/chatcraft.org/issues/13#issuecomment-1566012948).  I assume you mean "shared" chats?

**Comment by tarasglek** [comment]
> > 5. should we have server-side convos too?
> 
> I was including because [you mentioned it above](https://github.com/tarasglek/chatcraft.org/issues/13#issuecomment-1566012948). I assume you mean "shared" chats?

yes sorry. i think it was a typo for shared chats
