### ISSUE TITLE
Explain why chatcraft is good when asking for key

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#133]
I went through all the alternatives I could find. Was really hard too find motivation to try them because most of them including us don't explain what user gains for the effort of signing up.

List of features plus link to youtube demo would probably be a good start.

https://www.futuredesk.io/welcome seemed most honest but didn't sign up up for them cos unclear as to how pricing works

https://speechgpt.app/ signed up for that cos I thought they would have whisper voice understanding...but turned out I need azure keys for voice 🤡.

I think longer term we need some easy sign up and billing...eg login via github and get free credits and option to pay via stripe....but either way need better job at explaining value

**Comment by humphd** [comment]
I agree that the major limiting factor here is sign-up.  Most people aren't going to put their API key into a random web app (I wouldn't).

I think having the ability to do this is super powerful for people who understand how it all works and want to control cost.  However, most people would rather follow a more typical flow: sign-up, pay a one-time or subscription fee, start using the app.  We should probably consider giving people the ability to do either or.

For the text we use, I tried to get us a starting point using ChatCraft - https://chatcraft.org/c/humphd/CM1YTC8pn7gAR5301TzEc

What am I missing?

---

Welcome to **ChatCraft**! 🚀

ChatCraft (chatcraft.org) is your go-to platform for learning, experimenting, and getting creative with code through an intuitive chat interface powered by cutting-edge Language Learning Models (LLMs). Here's why you'll love ChatCraft:

🔧 **Versatile & Customizable**: Mix and match different LLM models in the same chat, control all aspects of the chat, and bring your own API key to manage your spending.

🌐 **Browser-based**: No installation required! ChatCraft works seamlessly in your browser.

🔒 **Privacy-focused**: All chats are stored locally in a searchable database, ensuring your data stays private and secure.

👩‍💻 **Familiar UI**: Designed with software developers in mind, ChatCraft's interface is inspired by GitHub, making it easy to navigate and use.

📝 **Markdown Support**: Edit and format your chats using GitHub flavored Markdown.

🔄 **Collaborative & Shareable**: Share your chats via public URLs, fork chats to explore new directions, and collaborate with others.

💾 **Export & Backup**: Download, copy, and export your chat data for safekeeping or further analysis.

🎉 **Open Source & Free**: ChatCraft is an open-source project, making it free for everyone to use and contribute to.

Ready to level up your coding skills? Sign up for ChatCraft today and unlock your full programming potential!

**Comment by tarasglek** [comment]
this is good. missed this update.

i think it would be interesting to add a competitive analysis table, to highlight features we have that others dont
