### ISSUE TITLE
Decide on update strategy for shared chats

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#143]
I want to explore how shared chats should work, specifically when it comes to updates.  Let me describe how this works at the moment.

You create a chat and decide to share it.   Let's say the chat is https://chatcraft.org/c/KlRWLA8H85RXSrmdgyEIh locally.  You get a public URL, let's say https://chatcraft.org/c/humphd/KlRWLA8H85RXSrmdgyEIh (note the addition of the username `/humphd/` in the path).

When you (as the creator) go to https://chatcraft.org/c/humphd/KlRWLA8H85RXSrmdgyEIh, it will redirect you to https://chatcraft.org/c/KlRWLA8H85RXSrmdgyEIh, that is, you'll be going back to the chat you shared.  If you make a change, it will update the db AND also push that newly updated version to R2 as well.

This has confused @tarasglek, and even I got surprised by it today.  I wonder what the correct way to do this would be?

In the past, we said that we didn't want to have buttons that you had to click to "save" things, that everything should be automatic.  I extended this idea to shared chats, and if you make a change, it auto-updates them.

Should a shared chat be immutable?  Should you have to manually opt into updating it?  Should updates be automatic?

**Comment by tarasglek** [comment]
i find it hard to think of use-case for a mutable shared chat. I think it would make sense to force "duplicate chat" functionality when modifying a "shared" chat (ether one you shared on one shared with you)
