### ISSUE TITLE
Drop langchainjs in favour of official openai

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#156]
I was updating deps tonight and ran into a wall when I failed a build due to [deprecations and renaming in langchainjs v0.0.105](https://github.com/hwchase17/langchainjs/commit/90d7edebe91b27a75229c465013e72bd32394598).

It's not a huge deal, and I can do it, but this is probably a good time to ask: are we ever planning to use langchain?  Right now we don't.  We could in various places, which I've asked about in https://github.com/tarasglek/chatcraft.org/issues/119#issuecomment-1608536293.

@tarasglek can we put some thought into this?  If we aren't ever going to use it, I'll rip it out.  If we are, I'll do this refactor.

**Comment by humphd** [comment]
https://github.com/lgrammel/ai-utils.js is interesting, as is https://vercel.com/blog/introducing-the-vercel-ai-sdk.

**Comment by tarasglek** [comment]
I endorse ditching it for anything with decent functions support.

**Comment by humphd** [comment]
Reading the code for these, I don't think either is perfect for what we need.

I think what I'm going to do is isolate our code even further from Langchain in order to prepare for a time in the future when we replace it with something different.

For now I'll stick with it.

**Comment by tarasglek** [comment]
langchain both hurt us in adoption of openrouter (eg broke us where we couldn't do workarounds) and made it easier to argue for them to fix support for it :)

I think it's either official openai api or langchain. I would prefer official openai api.

**Comment by humphd** [comment]
Official OpenAI node module is not really aimed at browsers, see https://github.com/openai/openai-node#openai-nodejs-library, though work seems to be happening in v4 https://github.com/openai/openai-node/issues/102#issuecomment-1627892242.

I'd like to move forward with my changes in #165, can you review that?  Regardless of what we do, those changes will help isolate us from how the AI pieces work, and make switching easier.

**Comment by tarasglek** [comment]
Lets switch to raw openai. Langchain/openrouter compat is too painful. I want to be able to say that we support llama, but can't atm. it's too glitchy

**Comment by humphd** [comment]
Adding some more context to this, in case it's helpful. We largely isolate our use of langchain to a few spots (mostly in anticipation of this issue being solved).  See:

https://github.com/search?q=repo%3Atarasglek%2Fchatcraft.org%20from%20%22langchain%2F&type=code

The first place you'd need to start work on this is in `src/ai.ts`, where we call it directly.  The code in there is a bit messy due to way that the langchain APIs work, and likely could be simplified.

The second place to look at is replacing our use of langchain's `MessageType` with our own type (i.e., pull it into our code vs. importing).

The third thing to evaluate are the `.toLangChain()` functions on `ChatCraftChat` and `ChatCraftMessage` classes.  We use these now to reshape our internal objects for use with LangChain, and if we move to something else, we'll likely want to rename and update these so they use the new format.

Let me know if there is more I can help untangle here.

**Comment by humphd** [comment]
This is complete, closing.
