### ISSUE TITLE
How to make chat wider?

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#158]
I'm quite bad at css. I'm staring at inspector and have no idea at how to make the chat take up whole screen.

<img width="1674" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/91cd9ce5-7ede-4d13-a73d-17d0182e1e2a">

**Comment by WangGithub0** [comment]
I wanna try this one.

**Comment by humphd** [comment]
@WangGithub0 sure, sounds good.  I wonder if the "right" fix here is actually to add a "Maximize" button and/or menu option to a message, so it can fill the viewport.  It would not be the default, but could be enabled by clicking the UI?

**Comment by humphd** [comment]
I mean something different--I know I said this above in my earlier comment.

What I'm suggesting is that we consider adding a way to show the contents in a wider view temporarily.  For example, with HTML views, we have an "Open in New Tab" button:

<img width="879" alt="Screenshot 2024-01-23 at 10 18 06 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/8021ccbb-6d5d-4a77-a51c-7b909e8c6542">

This opens the web page full width in a new tab.

We could do this for code blocks (or maybe even whole messages):

<img width="873" alt="Screenshot 2024-01-23 at 10 18 35 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/b9ca7742-c5b9-4ddb-ad0e-d0216a4decf8">

We'd generate a new Blob URL for the contents we want to show (e.g., the code, or rendered Markdown) and then open that in a new tab, using the same code we have now to accomplish this.

This would let users work with really wide data when they need to, but not make the UI a mess for the other 99% of the cases.

**Comment by WangGithub0** [comment]
ok, I will add a <img width="23" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/20795443/d00fc7aa-e8d0-441f-956c-d6d27dd6bff4">  button near the code and open a new tab when the user click it.
do we still need the full-width setting? or maybe we can let user set a width value(like 70%, 80%) which may solve Taras's issue in his screenshot.
