### ISSUE TITLE
Disable edit/delete for shared chats

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#160]
I was looking at https://chatcraft.org/c/tarasglek/cbo8qmybUrF9MwTIt8XBa, a shared chat I don't own, and noticed that the edit and delete buttons/icons are still there.  They don't do anything, since the chat is `readonly` (all shared chats are loaded from JSON vs. the db, so are read-only), but it's weird to have the user think that they can use them.

Places that need a fix:

1. Edit icon beside the chat's summary text
2. Edit and Delete icons when hovering a message
3. Edit and Delete menu options for a message

<img width="1119" alt="Screenshot 2023-07-10 at 2 17 42 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/70dbf6b3-38cb-4588-8a92-75ba9275a321">

**Comment by Chigala** [comment]
I'll love to pick up this issue if it hasn't been fixed already.

**Comment by humphd** [comment]
@Chigala it's still there, you're welcome to go for it.
