### ISSUE TITLE
Github signin issue

### ISSUE THREAD

**Issue by steven4354** [tarasglek/chatcraft.org#175]
**Issue**

I tried to sign in with my other github acct, but even after authorizing it doesn't connect to chatcraft.

Tested on normal chrome browser and a new incognito window. Also tried doing it in a separate fresh chrome profile but still not working

**Demo/How to Reproduce**

https://drive.google.com/file/d/1yhWhMAjPZf1XdaOvqSpuyif_Q0DBWoHF/view?usp=sharing

Steps:
- Sign out of GH account
- Use another GH account to sign in
- Authorize the GH oauth page
- Go back to chatcraft
- Still not connected + unable to share prompts

**Comment by humphd** [comment]
@steven4354 I don't have a second GH account to test this (@tarasglek, do you?).  I suspect there must be something weird happening in the backend functions, or GH is not happy somehow, but I can't get old logs from Cloudflare Pages.

Maybe we should co-ordinate when we have time and I can watch the logs live as you do this.

That Dropbox video isn't public (I don't have an account).  Can you drag it into this issue instead?

**Comment by steven4354** [comment]
Hi @humphd sure thing - I just updated the video link to a gdrive link instead (the video was too large for github upload), lmk if there still any access issues

Happy to hop on a call, in case it works, I have a calendly here: https://calendly.com/steven-239/chat-scheduling-1
