### ISSUE TITLE
Add syntax for forcing LLM to use a function

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#177]
In #172 we're adding support for function calling, introducing the `@fn: name` or `@fn-url: https://...` syntax to include references to `functions` in a chat when sent to OpenAI.

The way function calling works, you can also also set the `function_call` parameter.  By default it's value is `auto`, meaning that the LLM can decide to use or ignore the functions.  You can also set it to `none` (don't use any functions) or `{"name": "function-name-to-call"}` to force it to use a function.

It might be nice to add a way to signal your intention to do this when referring to the function.  For example, one of these:

```
@fn: foo!
@fn!: foo
@!fn: foo
```

I think putting it at the end might work `@fn: foo!`, as it feels a bit like `!important` in CSS.

If a function is referred to with this special syntax, we'd add that to the `function_call` property we send to the model.

What do you think?

**Comment by tarasglek** [comment]
it's confusing, @force-fn-url would be easier to understand

**Comment by humphd** [comment]
I'm not a fan of `force-` but I get what you're saying.  What about `required`:

```
# foo is optional (could be called)
@fn: foo
# foo is required (must be called)
@required-fn: foo
# foo is required (must be called) - alternate short-hand
@!fn: foo
```

**Comment by tarasglek** [comment]
Sure. Other idea is to have it in [retry] options... I've had cases where openai called the function when i didn't want to call it, so choosing 'none' would've been handy too. I also like the idea of keeping terminology same as upstream
