### ISSUE TITLE
Show function-loading errors

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#191]
<img width="1263" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/9425e73a-aa6b-4b16-b1ba-1d124eec4e5f">
Atm chatcraft just pretends nothing is wrong and ignores the url in the response..but in console can see that stuff went wrong.

**Comment by humphd** [comment]
So this is when you use a `fn-url` and it fails to parse what it gets, due to some bug in the code?

**Comment by tarasglek** [comment]
yes

**Comment by humphd** [comment]
I guess I could store the `err` on the `ChatCraftFunction` as an extra piece of data (i.e., put it on object, not store in db), and if it exists at runtime, show it in the UI somehow?

Have to think about when and where to show that info.

**Comment by tarasglek** [comment]
i think it should be same as openai api failing. currently we flash a red error message for those. Ideally we'd have a more permanent error
