### ISSUE TITLE
Help Wanted: ChatCraft User Feature Requests

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#194]
@tarasglek and I have spent the spring and summer implementing what *we* want in ChatCraft.  I think we've ended up making something pretty great.

However, I'd be interested to hear what *you*, our users would like to see us to do next.  If you're using ChatCraft and have suggestions, please add a comment here.  What would make this app better for you?  What would get your friends and colleagues to start using it?  How can we improve it for your needs?

No promises, but it would be great to build a list.

**Comment by rashboldb** [comment]
> > I'd really love to see it has some ASR system support, like Whisper!
> 
> Can you describe this a bit more?

I'd like to have the ability to communicate with chat (I can imagine it'll be mostly via mobile) with my voice. So once I can do this I can use it like [audiopen](https://audiopen.ai/) (pretty cool stuff) by modifying the prompt and let's say asking it to summarize & clean up my thoughts. It's only the example, and it's definitely not the most technical use case of the chat (which was the original idea, as far as I know) but that'll be awesome:)

**Comment by rashboldb** [comment]
BTW, someone already [did](https://github.com/chengsokdara/use-whisper) react hook for smth like this in the past, open source, it was update like 5 month ago the last time though.

**Comment by humphd** [comment]
Right, I've seen that hook before, it might be a good option.  I'll do some reading...

**Comment by tarasglek** [comment]
I think he means something like https://gitlab.com/attention1/ai-interface

**Comment by steven4354** [comment]
i'd love the ability to save the system messages to my profile so I can quickly swap between a few system messages I have (perhaps via a dropdown) and set a "default" system message to use whenever I open new blank chats

**Comment by humphd** [comment]
> i'd love the ability to save the system messages to my profile so I can quickly swap between a few system messages I have (perhaps via a dropdown) and set a "default" system message to use whenever I open new blank chats

I'm literally working on this right now!  I'll have a PR up soon, and you can help me figure out the UX, it's tricky to get right and make clear to users...

**Comment by humphd** [comment]
Also, "ability to set system prompt default" is #138

**Comment by humphd** [comment]
https://github.com/tarasglek/chatcraft.org/pull/196 is up with a partial fix for system default messages.

**Comment by alexisargyris** [comment]
Here are a few random thoughts:

* the UI looks nice and is quite flexible (small/large screen, landscape/portrait, etc.). Sometimes, when entering code, it doesn't get properly formatted or a line at the top or bottom gets skipped
* being able to expand/collapse all/some questions/answers might prove useful when space is limited 
* I am not sure I understand how the little chat summaries are produced. Maybe that area could be improved 
* the search box at the top would be more useful if I managed to have more saved chats but for some reason, they keep getting lost.
* my main problem though, is with the underlying model, not ChatCraft. I use gpt-4-0613 and it gets continuously in vicious circles or gives me the first answer that "crosses its mind" without considering alternatives only to backtrack later on. I have tried, and it doesn't look as if this can be solved from the side of ChatCraft (i.e. with elaborate prompting). For the time being at least, the model just forgets (parts of) its prompt, if it becomes too complex. I don't know if other people have difficulties in this area.

But, in general, ChatCraft is already just great!

**Comment by humphd** [comment]
@alexisargyris we've made a tweak to how the New button works, such that old chats are never lost by accident any more.

The summaries are something I'd like to improve, see https://github.com/tarasglek/chatcraft.org/issues/139.

**Comment by humphd** [comment]
ASR is done in #241! Try it out @rashboldb.

**Comment by rashboldb** [comment]
> ASR is done in #241! Try it out @rashboldb.

I'll play with it a little and provide you with feedback in a few days:)

**Comment by alexisargyris** [comment]
@humphd lately, my saved chats number has been growing steadily so I suppose that this problem is now solved

**Comment by humphd** [comment]
> * I am not sure I understand how the little chat summaries are produced. Maybe that area could be improved

I've updated the way that summaries get generated in https://github.com/tarasglek/chatcraft.org/pull/250.

**Comment by kosty** [comment]
Some things I find pretty interesting and would love to see in ChatCraft as part of my daily usage:

* starred System Prompts export/import to GitHub repo (given that ChatCraft already had GitHub signup)
* python execution via WASM
* image generation via DELL-E

**Comment by humphd** [comment]
> * starred System Prompts export/import to GitHub repo (given that ChatCraft already had GitHub signup)

I wonder if we could do something similar to what we do with gists for functions?

> * python execution via WASM

We could use https://pyodide.org/en/stable/usage/quickstart.html, if someone wants to hack it in as an optional import, similar to how we're doing Taras' TypeScript parsing.

> * image generation via DELL-E

See #125, #279.  @mingming-ma is working on some related magic with the new multi-modal stuff in gpt-4

**Comment by humphd** [comment]
We've been able to do most of this now, closing.  Please continue in #317.
