### ISSUE TITLE
Fix z-index/overlap in iframe HTML examples

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#203]
When an example HTML page includes content in the top-right, it can cause issues with the "open in fullscreen" icon button:

<img width="875" alt="Screenshot 2023-08-10 at 11 26 38 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/d078d0cd-8b8d-4d9f-b9dc-c989da843523">

It would be good to find a way to add enough padding around this icon button so that it doesn't get lost.

**Comment by tarasglek** [comment]
Wow, that's quite a corner case 🥇
