### ISSUE TITLE
claude 2 100k

### ISSUE THREAD

**Issue by steven4354** [tarasglek/chatcraft.org#226]
was curious if chatcraft could support claude 2 100k, I find I've been using claude 2 a lot on html.

would be very useful if i can do iterate the outputs via a chat UI like chatcraft

this is my test scaffold I've been using claude 2 100k with: https://github.com/steven4354/anthropic-test/blob/main/test_html_100k.ts

the only supports 1 message right now unfortunately which makes it hard to iterate when the first output from claude 2 is wrong

**Comment by humphd** [comment]
Does it work with OpenRouter? See https://openrouter.ai/docs for the list of what they support.  Anything you can run with them we can do.

**Comment by steven4354** [comment]
Does open router allow me to use my own api key like chatcraft? I have my own Claude 2 100k keys

**Comment by steven4354** [comment]
I see here it says it supports Claude v2 

But I'm not sure if that is the 100k version

![image](https://github.com/tarasglek/chatcraft.org/assets/28765991/d2d9b044-7849-4c8f-a31a-3993edbdd039)

**Comment by humphd** [comment]
cc @tarasglek, I know very little about our OpenRouter impl

**Comment by steven4354** [comment]
Also says here it can use the openai keys

Have you used openrouter on chatcraft before? Is it good?

![image](https://github.com/tarasglek/chatcraft.org/assets/28765991/d7516c5c-5284-4ea2-b381-a3abab2a420d)

**Comment by tarasglek** [comment]
Openrouter is fantastic when it works. Problem is that between langchain and their changes it rarely works. We are moving off langchain so I can pin them down easier, give them a test case so we can keep working.

**Comment by ishaan-jaff** [comment]
Hi @tarasglek @steven4354 I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
If you don't have access to the LLM you can use the LiteLLM proxy to make requests to the LLM**

You can use LiteLLM in the following ways:

## With your own API KEY:
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
os.environ["COHERE_API_KEY"] = "your-key" # 

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

## Using the LiteLLM Proxy with a LiteLLM Key 
this is great if you don’t have access to claude but want to use the open source LiteLLM proxy to access claude


```python
from litellm import completion
import os

## set ENV variables 
os.environ["OPENAI_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your openai key
os.environ["COHERE_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your cohere key

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

**Comment by humphd** [comment]
@ishaan-jaff this is interesting.  We added support for OpenRouter.ai for a similar reason, and I think LiteLLM looks similarly interesting for our use case.

A long-standing feature we've been slowly working toward adding is support for more and arbitrary backends.

I'm going to add LiteLLM to the list of supported ones we include in the list.

**Comment by ishaan-jaff** [comment]
@humphd if Openrouter solved that problem why add LiteLLM ?

**Comment by humphd** [comment]
> @humphd if Openrouter solved that problem why add LiteLLM ?

Choice, ability to try different backends, decoupling from providers who may or may not exist in the future, etc.

**Comment by steven4354** [comment]
Did OpenRouter get into Chatcraft? I don't remember using it on Chatcraft before

Was there some issues with openrouter? Maybe @ishaan-jaff gets the info on openrouter s drawbacks he could make liteLLM good enough for chatcraft use

Just throwing out random ideas if it'd possibly make things easier to add more model support. Not sure if helpful!

**Comment by humphd** [comment]
> Did OpenRouter get into Chatcraft? I don't remember using it on Chatcraft before

<img width="506" alt="Screenshot 2023-09-22 at 5 55 08 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/b1cd021d-2f1a-45f1-b54e-a30d9a984f47">

You can use either OpenAI or OpenRouter.ai currently.

**Comment by steven4354** [comment]
Ah I see, that's great I didn't see it in the settings. i'll test that out
