### ISSUE TITLE
Investigate and fix OpenRouter issue.

### ISSUE THREAD

**Issue by iramykytyn** [tarasglek/chatcraft.org#228]
See details at Known Issue [here](https://github.com/tarasglek/chatcraft.org/pull/220).

**Comment by tarasglek** [comment]
Problem is on the openrouter side. Raised it with them. Openai sends some tracking headers for stainlessapi.com and they make openrouter unhappy

https://discord.com/channels/1091220969173028894/1138521849106546791/threads/1147809378423025674

**Comment by tarasglek** [comment]
fixed it on openrouter side

**Comment by humphd** [comment]
Can we close, or is there more to happen here?
