### ISSUE TITLE
GitHub sign-in doesn't work with Cloudflare preview links.

### ISSUE THREAD

**Issue by iramykytyn** [tarasglek/chatcraft.org#229]
GitHub sign-in doesn't work with Cloudflare preview links, so testing related functionality (like Share) is impossible until it is in production.

https://github.com/tarasglek/chatcraft.org/assets/6651168/357f0a5b-3ee3-415c-9c37-f1b2fce3efb9

**Comment by humphd** [comment]
The code to make that work landed in #217, is the branch you're trying to test properly rebased?

NOTE: once rebased, you can also do this in local development with `pnpm dev-functions`.

**Comment by humphd** [comment]
@iramykytyn is this still an issue?  I'm able to sign-in for a recent PR preview branch: https://dep-updates-sep-7-2023.console-overthinker-dev.pages.dev

**Comment by humphd** [comment]
Re-open if this appears again.
