### ISSUE TITLE
Use OpenRouter User Limits API to check key

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#230]
When a user enters an API key for OpenRouter, we need a way to check that it's good.  It looks like we could use https://openrouter.ai/docs#limits

**Comment by kliu57** [comment]
@humphd Can I work on this issue?

**Comment by humphd** [comment]
Sure, go for it.  Another thing you could work on that's related is that when the user is entering a new API key, let's say for OpenAI vs. OpenRouter, we don't want to send the stored key to the other provider.

There's a bunch of things we could improve in how this is all done.

**Comment by kliu57** [comment]
> Sure, go for it. Another thing you could work on that's related is that when the user is entering a new API key, let's say for OpenAI vs. OpenRouter, we don't want to send the stored key to the other provider.
> 
> There's a bunch of things we could improve in how this is all done.

Ok, I can create another issue for this
