### ISSUE TITLE
Use proper function call and result message serialization format for OpenAI

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#235]
Follow-up from https://github.com/tarasglek/chatcraft.org/pull/220#issuecomment-1694706762 and https://github.com/tarasglek/chatcraft.org/pull/223#issuecomment-1696859726: I don't think we're serializing function call and result messages properly to the format OpenAI expects.

See changes to `ChatCraftMessage.ts` in https://github.com/tarasglek/chatcraft.org/pull/220/files#diff-c5e959cfbbe3d92b50356acefecf790bea69d21cc6800bdc040d750ed68ac41d.

The OpenAI SDK has some examples we should read through more closely:

- https://github.com/openai/openai-node/blob/master/examples/function-call.ts
- https://github.com/openai/openai-node/blob/master/examples/function-call-stream.ts

**Comment by tarasglek** [comment]
I think we need to split raw storage of message from rendered version.
1) we render it for user, eg we render openai func calls into markdown.
2)  We then wanna send it back to openai in original form
3) we also render message into openai..eg when we ask openai to call a function, we should replace our special function call syntax with url with function_name()

**Comment by humphd** [comment]
Fixed by #238
