### ISSUE TITLE
Experiment with voice input

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#237]
Spin-off from https://github.com/tarasglek/chatcraft.org/issues/194#issuecomment-1660385933. We'd like to explore integrating automatic speech recognition (ASR) into ChatCraft.

I've read the code for many of the existing React components that can do this, and they are all demo quality and largely unmaintained.  Someone might be able to find one that's actually being developed, but if not, we should build our own.

We could use a cloud-based model via API, but we could also consider doing this entirely in the browser using an ONNX or WASM version of Whisper, for example https://github.com/microsoft/onnxruntime-inference-examples/tree/main/js/ort-whisper or https://whisper.ggerganov.com/ (there are others).

If we run a model in the browser, we'd need to figure out some UX for letting the user opt-in to downloading it (i.e., don't do it on load), and giving mic access.

**Comment by tarasglek** [comment]
if you wire up a microphone button to input box for me..that you can press down, release and dummy text gets put into input box, i'll do the the rest

**Comment by humphd** [comment]
So to clarify:

- You press a "mic" button near the input box, and it starts a recording.
- You stop the recording by pressing it again (or a "stop" button)
- The audio then gets processed (i.e., after you press "stop")
- The processed audio is displayed in the input

Other implementations I've see try to do fancy things with listening for silence and trying to figure out when to stop the recording, etc. but they all seem to only partly work.

I never use speech input, so I don't have much UX experience.  If you can be clear about what you want for the above, I'll do a UI shell for you to slot in your audio processing logic.

**Comment by tarasglek** [comment]
I imagine it working like voice messages in chat apps. 
0. Ideally mic would live on rightmost position within [input box________🎤], but to the right of it fine too.
1. On mobile it's best to hold down mic button while making recording. 
2. You let go of mic button, recording gets sent to openai
3. Processed audio is appended to inputbox

**Comment by tarasglek** [comment]
You drag the microphone left to abort..but we can skip abort functionality for now

**Comment by humphd** [comment]
This is some impressive optimizing of the ONNX whisper model https://twitter.com/xenovacom/status/1698742891118493905

**Comment by tarasglek** [comment]
> This is some impressive optimizing of the ONNX whisper model https://twitter.com/xenovacom/status/1698742891118493905

indeed
