### ISSUE TITLE
Keep track of, display audio recording time

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#249]
Let's include info about how long we've been recording audio and display it in the prompt form's hint text, something like:

Recording 00:13 ...

Knowing this time will also help us to update the cost info.  Whisper costs $0.006 / minute (rounded to the nearest second).

**Comment by tarasglek** [comment]
i would like to have the whole textbox turn into an audioform or some sort indicator of recording. it's really unintuitive atm to see if i pressed the mic. The label says recording, but soul desires more :)

**Comment by humphd** [comment]
Done and shipped

**Comment by tarasglek** [comment]
this has been really nice to use
