### ISSUE TITLE
Can't record on android

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#252]
![Screenshot_20230920_104333996_Brave.jpg](https://github.com/tarasglek/chatcraft.org/assets/857083/62262dee-be94-4c81-9955-ec501399faee)

**Comment by humphd** [comment]
I don't have access to Android to test this, but the failure is happening in https://github.com/tarasglek/chatcraft.org/blob/8070bf0707f0555ef4a7e78ed75da2bcf446fc95/src/components/MicIcon.tsx#L87

Based on the error message in the screenshot, we're likely failing in https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/speech-recognition.ts#L134, and based on https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/state, this can throw if the recording isn't happening.  It's weird that you'd already be in `state=inactive` when `.stop()` is called.  What was the sequence of events that got you to this point?  Does it always happen?

An obvious fix here would be to check the state before we call `.stop()` or `try/catch`.
