### ISSUE TITLE
Configuration/Settings model parameters

### ISSUE THREAD

**Issue by hypzz** [tarasglek/chatcraft.org#266]
I have a feature request: It would be useful for me to be able to configure the temperature and presence/frequency penalties sent to the model when generating. These parameters are described in detail in the following link: [Parameter Details](https://platform.openai.com/docs/guides/gpt/parameter-details)

I would love to have the ability to tweak these parameters on a per-chat basis, but even having them globally configurable in the user settings would be acceptable.

[By the way, I am really enjoying ChatCraft so far... thank you!]

**Comment by tarasglek** [comment]
Hi, thanks for feedback. Would you be interested in contributing this?

**Comment by humphd** [comment]
@hypzz happy to give guidance as needed.  But also, don't be afraid to use ChatCraft for help; that's what we do ;)
