### ISSUE TITLE
All the languages in the world are loaded eagerly

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#27]
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/857083/235229037-a55f0fe9-d9b6-44b8-a253-94bd05adea63.png">

**Comment by humphd** [comment]
This is the service worker precaching languages for offline use.  I think it's good (load them once, never again); but we can tweak how workbox does the network cache strategy.

See https://vite-pwa-org.netlify.app/guide/service-worker-precache.html.  We could also have it cache on-demand when we use them.

**Comment by humphd** [comment]
One thing we could do is explicitly precache only the common languages we care about, and then cache-on-download the others.  I think you'd define a glob for this here: https://vite-pwa-org.netlify.app/guide/static-assets.html#globpatterns
