### ISSUE TITLE
z-index problem for model menu

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#273]
The model menu should have a higher z-index than the "open in new window" button for an iframe preview

<img width="979" alt="Screenshot 2023-10-26 at 3 40 31 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/d5895ccd-d9a8-4981-8be5-eef8e4407f01">

**Comment by Amnish04** [comment]
@humphd I remember this as a follow up issue from my last contribution. If its okay for me to work on it, could you let me know of any preferences for the z-index?

**Comment by humphd** [comment]
Sure go for it @Amnish04
