### ISSUE TITLE
No horizontal offset for model menu on mobile screen

### ISSUE THREAD

**Issue by Amnish04** [tarasglek/chatcraft.org#274]
The model selection menu touches the rightmost end of the screen.

![278768073-37fc598a-d5c8-46bd-85c2-2e9ad64af198](https://github.com/tarasglek/chatcraft.org/assets/78865303/7231de23-7ce7-49c4-8449-4e21c1e9e25d)

There needs to be a small offset from the right side, such that its formation is correctly visible.

Follow up issue for #271

**Comment by Amnish04** [comment]
I can send a pull request if we need to address this issue.

**Comment by humphd** [comment]
@Amnish04 if you're willing to fix, that sounds great.
