### ISSUE TITLE
Continue the conversation when context window limit is reached

### ISSUE THREAD

**Issue by DukeManh** [tarasglek/chatcraft.org#280]
When the context window is limit is reached, how can we continue the conversation without switching to another model?

![image](https://github.com/tarasglek/chatcraft.org/assets/51073515/44bab8fa-edbd-4013-9ab9-5ab0c1b2ec92)

**Comment by humphd** [comment]
See discussion in https://github.com/tarasglek/chatcraft.org/issues/67
