### ISSUE TITLE
Add the TTS mode to work with voice input

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#283]
Would be nice to opt into chatcraft responding in voice when I ask stuff via voice.

**Comment by humphd** [comment]
I think this is fixed now, right?

I was also wondering yesterday if we should support an audio-only mode, where nothing gets displayed.  I wonder if that would be useful on mobile where you aren't looking at it.

**Comment by Amnish04** [comment]
> I was also wondering yesterday if we should support an audio-only mode, where nothing gets displayed. I wonder if that would be useful on mobile where you aren't looking at it.

That's a nice idea! We could have a radio button on top right in the header to switch between audio-only and normal modes. Might need to put some more thought into this.

**Comment by humphd** [comment]
Did we not solve this?

**Comment by tarasglek** [comment]
This
