### ISSUE TITLE
Type error while saving edits to System Prompt

### ISSUE THREAD

**Issue by kosty** [tarasglek/chatcraft.org#291]
Error seems to be pointing to this line 

https://github.com/tarasglek/chatcraft.org/blob/0b0ee516006a825ae18606b2d2390e4b55e5ddb3/src/components/Message/MessageBase.tsx#L207

`TypeError: Cannot read properties of null (reading 'removeAttribute')` is thrown like so

![Screenshot 2023-11-15 at 9 04 56 AM](https://github.com/tarasglek/chatcraft.org/assets/630193/d295172b-3418-4511-b280-1a05cf718881)

**Comment by humphd** [comment]
cc @DukeManh

**Comment by DukeManh** [comment]
Oops, I'll fix it.
