### ISSUE TITLE
When changing API key in User Settings, do not send stored key

### ISSUE THREAD

**Issue by kliu57** [tarasglek/chatcraft.org#307]
Sure, go for it.  Another thing you could work on that's related is that when the user is entering a new API key, let's say for OpenAI vs. OpenRouter, we don't want to send the stored key to the other provider.

There's a bunch of things we could improve in how this is all done.

_Originally posted by @humphd in https://github.com/tarasglek/chatcraft.org/issues/230#issuecomment-1852606536_

**Issue description** (Attempting to switch from OpenRouter to OpenAI):

When going to User Settings to change the API URL from the dropdown, do not send the stored key to the newly selected API URL provider the moment we select from the dropdown.

**Issue screenshots:**

![sendIssue1](https://github.com/tarasglek/chatcraft.org/assets/98062538/f96b97d6-50cb-4e3c-9f07-33f7c5401076)
![sendIssue2](https://user-images.githubusercontent.com/98062538/290310853-18a303f5-5505-4f3c-bec5-30ef8301bd4a.png)

**Expected behaviour:**

Please help me to clarify what should be the expected behaviour.

**Comment by humphd** [comment]
I think this is the flow I'd do, see what you think:

## Case 1: new user

- User has never used ChatCraft
- Goes to enter a key, there is nothing there
- We fill in the key as they type and save it once the validation has worked

## Case 2: existing user

- User already has a key in settings
- They come to settings and change the Provider.
- I think we should clear the key.  The down side of this is you lose your old key and have to re-enter it if you want to change back to the previous provider.  The positive side of this is that you don't leak that key to a different provider

Later we could support multiple keys in settings, storing each one with the provider name (e.g., `OPENAI_API_KEY` vs. `OPENROUTER_API_KEY, etc).

**Comment by kliu57** [comment]
@humphd Clearing the key sounds good. I can work on this.
