### ISSUE TITLE
Enable python, go, tsc, etc support via wasi

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#312]
Currently chatcraft works best with js and typescript(thanks to esbuild wasm). It enables complete idea->prototype workflow including the debug cycle where gpt automagically infers fixes inside the chatcraft. However once you get into go/python, it's a lot less satisfying due to having cut/paste code between chatcraft and editor.

Lets solve this the next couple of languages, see https://snarky.ca/wasi-support-for-cpython-june-2023/ here for more details on python

**Comment by tarasglek** [comment]
Looks like most work was already done https://antonz.org/in-browser-code-playgrounds/

**Comment by tarasglek** [comment]
Looks like for go we should use the official go playground as it supports modules https://go.dev/play/p/XCoNXEjm3TS

**Comment by humphd** [comment]
I think a good first step here would be to try integrating the https://github.com/nalgeon/python-wasi code so we can run arbitrary Python.  See his other `*-wasi` modules too https://github.com/nalgeon?tab=repositories&q=wasi&type=&language=&sort=

**Comment by humphd** [comment]
Here is his online version of the `python-wasi` stuff for experiments: https://codapi.org/embed/?sandbox=python (see `Run` button at bottom to execute).

**Comment by tarasglek** [comment]
Related https://urllib3.readthedocs.io/en/stable/reference/contrib/emscripten.html

**Comment by WangGithub0** [comment]
> https://github.com/nalgeon/python-wasi

Tested this python-wasi, it worked on my computer using this test:
```
const url = "https://unpkg.com/@antonz/python-wasi/dist/python.wasm";

const pythonScript = `
a = 1
b = 2
c = a + b
print(c)
print("Hello World!")
`;

import("@antonz/runno").then(({ WASI }) => {
    WASI.start(fetch(url), {
        args: ["python", "-c", pythonScript],
        stdout: (out) => console.log(out),
        stderr: (err) => console.error(err),
    }).then(result => console.log(`exit code = ${result.exitCode}`));
});
```

```
Output:
3
Hello World!

exit code = 0
```




@humphd  should I combine this in `src/lib/run-code.ts` file to support run a python file in a chat? Should I also add this in `src/lib/ChatCraftFunction.ts` to support add python function?

**Comment by tarasglek** [comment]
yes that seems like the way @WangGithub0

**Comment by WangGithub0** [comment]
@tarasglek @humphd  In order to support python in [ChatCraftFunction](src/lib/ChatCraftFunction.ts), should we also create a package which is similar to [typescript2openai](https://github.com/tarasglek/typescript2openai/tree/main) and require user to add the parameter types into python comments?

**Comment by tarasglek** [comment]
chatcraft functions are a niche feature for now, lets focus on other features like custom openai-compatible providers, sharing improvements, etc

**Comment by tarasglek** [comment]
To be clear, lets wait and see how much people use python support and evolve future python related functionality based on demand. wasi is really cool, but wanna wait and see on it.

If you want to work more on wasi type stuff, would be cool to get golang working via wasi in same way

**Comment by tarasglek** [comment]
I would also add server-side execution for python and go, as it likely allows using libraries and network access. codeapi is good for that, eg open https://codapi.org/go/ example in network tools. They have a CORS friendly api.

**Comment by WangGithub0** [comment]
I think I can add more *-wasi (https://github.com/nalgeon?tab=repositories&q=wasi&type=&language=&sort=) in run-code and then add server-side execution for python and go

**Comment by tarasglek** [comment]
use free while in beta one

**Comment by WangGithub0** [comment]
> if you look at how the examples on the codeapi homepage run, they use cors and we can use same endpoint. If this becomes an issue i will self host

I'm afraid we have to do the self-hosted, could it run on Cloudflare?

**Comment by tarasglek** [comment]
why do you say that we have to do our own?

**Comment by WangGithub0** [comment]
> why do you say that we have to do our own? (not doubting, just wanna know technical reason)

Since Codeapi cloud is currently in private beta and not free for serve and support, there's a risk of changes beyond our control. Self-hosting offers stability and control over our endpoints, particularly in the long term. If you're interested in exploring it, I can test it once you request access.
