### ISSUE TITLE
TeX and KaTeX interpretation

### ISSUE THREAD

**Issue by kosty** [tarasglek/chatcraft.org#313]
I can't reproduce it right now, however I had ChatCraft output beautiful formulas when I prompted it to use KaTeX syntax some time ago. Right now this does not seem to be working any more. I wonder if something changed? If not we should add that functionality, TeX is notoriously had to interpret as a source code

![Screenshot 2023-12-29 at 9 55 27 AM](https://github.com/tarasglek/chatcraft.org/assets/630193/319a5ee1-c761-4b12-99d4-74948d7d0dd6)

Here's the link
https://chatcraft.org/c/kosty/D1kmkQfuQM7z3woeTAhIi

Here's a quote

> Lp normalization is a process used to scale the elements of a vector or matrix such that the p-norm (also known as the Lp norm) of the vector or matrix is equal to 1. The p-norm of a vector is defined as:
> 
> \[\|x\|_p = \left( \sum_{i=1}^{n} |x_i|^p \right)^{1/p}\]
> 
> where \(x\) is a vector with \(n\) elements, \(x_i\) is the \(i\)-th element of \(x\), and \(p\) is a real positive number.
> 
> To Lp normalize a vector, you divide each element by the p-norm of the vector. Here's how you can implement Lp normalization over a specified dimension of a matrix in Python using NumPy:
> 
> ```python
> import numpy as np
> 
> def lp_normalize(matrix, p, axis):
>     # Calculate the Lp norm of the matrix over the specified axis
>     lp_norm = np.linalg.norm(matrix, ord=p, axis=axis, keepdims=True)
>     
>     # Avoid division by zero
>     lp_norm[lp_norm == 0] = 1
>     
>     # Normalize the matrix
>     normalized_matrix = matrix / lp_norm
>     
>     return normalized_matrix
> 
> # Example usage:
> matrix = np.array([[1, 2, 3], [4, 5, 6]])
> p = 2  # Euclidean norm (L2 norm)
> axis = 1  # Normalize over rows
> 
> normalized_matrix = lp_normalize(matrix, p, axis)
> print(normalized_matrix)
> ```
> 
> In this example, `lp_normalize` is a function that takes a matrix, a value of `p` for the p-norm, and an `axis` over which to perform the normalization. The function calculates the p-norm using `np.linalg.norm` with the `ord` parameter set to `p` and `axis` set to the specified axis. The `keepdims=True` argument ensures that the result has the same dimensions as the input matrix for broadcasting during division.
> 
> The function then divides the original matrix by the p-norm to normalize it. If any p-norms are zero (which can happen if all elements along an axis are zero), the function sets them to 1 to avoid division by zero.
> 
> The `axis` parameter determines the dimension over which to calculate the norm:
> 
> - If `axis=0`, the function normalizes each column.
> - If `axis=1`, the function normalizes each row.
> 
> The example usage normalizes each row of a 2x3 matrix using the L2 norm (Euclidean norm).

**Comment by tarasglek** [comment]
would be helpful to go through your chat history and find ones that worked

**Comment by kosty** [comment]
Here you go

https://chatcraft.org/c/kosty/yzn4mCD5z9Fc7VSvUQr8a

![Screenshot 2023-12-29 at 10 26 31 AM](https://github.com/tarasglek/chatcraft.org/assets/630193/87a906b8-ae48-4122-b9a3-bf6f0531e254)

> Sure, let's break down these concepts:
> 
> 1. **Accuracy**: This is the proportion of true results (both true positives and true negatives) in the population. It is a measure of the correctness of a classification model on the total input data. Mathematically, it can be represented as:
> 
>    ![Accuracy Formula](https://latex.codecogs.com/svg.latex?Accuracy=\frac{TP+TN}{TP+FP+TN+FN})
> 
> 2. **Precision**: This is the proportion of true positive results in the population of all positive results. It is a measure of the correctness achieved in positive prediction of the model. Mathematically, it can be represented as:
> 
>    ![Precision Formula](https://latex.codecogs.com/svg.latex?Precision=\frac{TP}{TP+FP})
> 
> 3. **Type 1 Error (False Positive)**: This is when we reject the null hypothesis when it is actually true. In terms of classification models, it is when we predict an event that doesn't happen.
> 
> 4. **Type 2 Error (False Negative)**: This is when we accept the null hypothesis when it is actually false. In terms of classification models, it is when we don't predict an event that does happen.
> 
> Here is how they are related:
> 
> - A model with high accuracy and precision has low Type 1 and Type 2 errors.
> - A model with high Type 1 error will have low precision because precision is about minimizing false positives (Type 1 error).
> - A model with high Type 2 error will have low recall because recall is about minimizing false negatives (Type 2 error).
> - Accuracy takes into account both Type 1 and Type 2 errors. A model with high accuracy will have both low Type 1 and Type 2 errors.
> 
> Here is a visual representation of these concepts:
> 
> ```mermaid
> graph LR
> A[Accuracy] -- depends on --> B[True Positives]
> A -- depends on --> C[True Negatives]
> A -- depends on --> D[False Positives]
> A -- depends on --> E[False Negatives]
> F[Precision] -- depends on --> B
> F -- depends on --> D
> G[Type 1 Error] -- is --> D
> H[Type 2 Error] -- is --> E
> ```
> 
> In the diagram, TP = True Positives, TN = True Negatives, FP = False Positives, and FN = False Negatives.
>

**Comment by kosty** [comment]
Basically formula's a visualized by passing formula to latex.codecogs.com like this

```
![Accuracy Formula](https://latex.codecogs.com/svg.latex?Accuracy=\frac{TP+TN}{TP+FP+TN+FN})
```

**Comment by kosty** [comment]
![Lp Formula](https://latex.codecogs.com/svg.latex?[|x|p = \left( \sum{i=1}^{n} |x_i|^p \right)^{1/p}]

**Comment by humphd** [comment]
I think you're at the mercy of the model to choose to use https://latex.codecogs.com/svg.latex or not unless you add that to your system prompt, similar to how we do for Mermaid diagrams.  Try adding:

- Always use https://latex.codecogs.com/svg.latex to render TeX, LaTeX, etc as an image in Markdown responses

**Comment by tarasglek** [comment]
whoa..neat way to inject diagrams

**Comment by kosty** [comment]
The prompt line @humphd mentioned works great thus far. I guess I'll close the issue for now, unless there are other concerns

**Comment by humphd** [comment]
Awesome, glad it's working for you.

**Comment by tarasglek** [comment]
Why not add this to default prompt?

**Comment by humphd** [comment]
Related: I wonder if we need a way to share these system prompts more easily, as we've discussed before, maybe even with a way to get them trending by upvoting.

I have really loved our default prompt, but lately I've been updating it to overcome issues in certain models.

**Comment by tarasglek** [comment]
I would love to keep up with your prompt hacks, i got some fun ones too

**Comment by humphd** [comment]
@kosty you'll love this: my eldest daughter just came into my office telling me that I needed to fix ChatCraft so it worked for rendering math equations.  I pulled up this image, copied your stuff for her, and she's thrilled.

"Dad, now you need to make it easy to share these system prompts!"  Amen.
