### ISSUE TITLE
Package and ship typescript2openai on npm

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#321]
We use https://github.com/tarasglek/typescript2openai for our Function Calling to generate an OpenAI compatible function using TypeScript.  Currently we use a hacky method for including this, see https://github.com/tarasglek/chatcraft.org/blob/main/package.json#L47.

Let's properly set up the packaging and CI/CD for that repo so that it publishes to npm and we can pull it in like a normal npm dependency.

**Comment by WangGithub0** [comment]
I wanna try to do this one.

**Comment by humphd** [comment]
@WangGithub0 excellent.  Here are some thoughts on how I'd approach this.

- @tarasglek will need to [create an NPM Token](https://docs.npmjs.com/creating-and-viewing-access-tokens) and put it in the GitHub Actions Secrets of https://github.com/tarasglek/typescript2openai using a name like `NPM_TOKEN` or something that gets communicated to you, so you can use it via `${{ secrets.NPM_TOKEN }}` in GitHub Actions.
- The [build](https://github.com/tarasglek/typescript2openai/blob/main/package.json#L9) should probably get updated so that it produces both ESM and CommonJS versions, as well as TypeScript types.  My suggestion is that you use [unbuild](https://github.com/unjs/unbuild) for this, which will do this for you without much work
- The `package.json` will need to get updated so that it has a `files` key, which will list the files/folders to publish (e.g., `dist` and `README.md` are probably enough)
- Create a GitHub Action that runs whenever a new `release` is created.  If you want to also create a second GitHub Action to run the tests whenever there is a PR or merge to main, that could be a good follow-up or even first step.
- In this release action, you will checkout the code, install pnpm, build, and then call [`pnpm publish`](https://pnpm.io/cli/publish)
- @tarasglek (or anyone who has rights over the repo) would then [create a new Release and Tag](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

**Comment by humphd** [comment]
This seems doable by 1.1 (next Friday) assuming @tarasglek has time to work on the token setup.
