### ISSUE TITLE
Package and ship github-to-sops with pip

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#324]
We're using sops and GitHub to secure secrets in the repo, and @tarasglek has created a neat Python tool to make it easier to do: https://github.com/tarasglek/github-to-sops. Let's get this packaged so it can be installed with `pip`

**Comment by tarasglek** [comment]
https://simonwillison.net/2024/Jan/16/python-lib-pypi/ seems helpful

**Comment by humphd** [comment]
https://github.com/prefix-dev/rattler-build/blob/main/examples/rich/recipe.yaml for an example of doing this with rattler-build for conda.

**Comment by humphd** [comment]
https://github.com/tarasglek/github-to-sops/pull/2

**Comment by rjwignar** [comment]
I'd like to look into Willison's method

**Comment by humphd** [comment]
@rjwignar awesome, thank you.  I would suggest you continue work in the gitub-to-sops repo vs. here, but I'll leave this open as a tracking issue.

Don't pay attention to what I've done for rattler; do what Simon says to do.  The rattler build can leverage whatever you do with pip.

**Comment by humphd** [comment]
We should figure out which pieces of this we can get done by 1.1 (next Friday), even if we can't get it all in by then.

**Comment by rjwignar** [comment]
I recently made a [PR](https://github.com/tarasglek/github-to-sops/pull/3) that modifies `github-to-sops`'s directory structure to match that produced by Willison's [cookiecutter template](https://github.com/simonw/python-lib-template-repository).
Among other things, the cookiecutter template also adds a workflow that publishes package releases to PyPI.

Publishing to PyPI first requires filling a **Pending Publisher** form to use PyPI's [Trusted Publishers](https://docs.pypi.org/trusted-publishers/) mechanism. Here's an example form Willison used for one of his libraries:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/22f0d30d-09ff-4a96-8c48-0f4921ad3721)

I haven't tried it yet, but I think I'd be able to fill out and submit the form even though I'm not the repo owner.

**Comment by humphd** [comment]
@WangGithub0 do you want to review https://github.com/tarasglek/github-to-sops/pull/3 as well, since you did something similar for the TypeScript module?

**Comment by WangGithub0** [comment]
> tarasglek/github-to-sops#3

sure, I'll do it

**Comment by humphd** [comment]
@rjwignar can we close this now?

**Comment by rjwignar** [comment]
@humphd Thanks for reminding me.
I hadn't checked this issue in a while and thought it also required shipping github-to-sops to ChatCraft, but I re-read the issue and  everything's been completed. We can close it
