### ISSUE TITLE
Fix positioning, padding, sizing of images

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#333]
When rendering latex images in a message, the position, padding, and size could be improved:

<img width="899" alt="Screenshot 2024-01-13 at 11 30 57 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/6b36649d-6099-4d28-9c3d-1ced92e0ea67">

Here's an example chat:

https://chatcraft.org/c/humphd/HWrYbl4QNB52j3RNkyT4k

This likely happens for all images vs. the ones I'm doing here.

**Comment by mingming-ma** [comment]
Trying to use `remark-math` and `katex` related plugins to render the math, and it can also have better looks in dark mode: https://github.com/tarasglek/chatcraft.org/issues/335

Here is the look, 
![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/57d587e1-e954-42a5-beca-0265b92d82a4)

Not following all the chat history about this requirements, so I'm not sure it's suitable in this way to fix.

**Comment by humphd** [comment]
Seems like a nice improvement.  Did you have to alter your prompts to get it to give you this?

cc @kosty

**Comment by mingming-ma** [comment]
Oh, my bad, forget to mention that I added this

- formula in LaTeX by enclosing it with $$ display style

**Comment by humphd** [comment]
We could add that rule to the default system prompt if we end up shipping these plugins.

**Comment by humphd** [comment]
This is amazing:

<img width="925" alt="Screenshot 2024-01-17 at 8 48 26 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/c777ea2f-ef03-438e-9a82-c2332adae8f4">

<img width="917" alt="Screenshot 2024-01-17 at 8 48 51 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/4b10b985-0a7a-4132-aa25-cd6f4c808dde">

**Comment by kosty** [comment]
thanks for pointing to this @humphd ! it is awesome! already played with it via updated prompt
