### ISSUE TITLE
Change mobile interface to be easier to use. 

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#336]
We should change the button the left to be "burger" options menu. Should move share into it. Should also move edit system prompt into it...which would scroll up and do equiv of editing system prompt.

We should flip the way mic icon works...instead of holding to record should click it once to start recording and once to stop. This is how bing works on ios.

Should also edit mic icon to when we edit messages and system prompt. Can do that in a followup

Might also make sense to move model selection into this menu.

**Comment by kosty** [comment]
![IMG_2174](https://github.com/tarasglek/chatcraft.org/assets/630193/a885a775-524f-4e1f-a353-2e3881f401d4)

side menu of the message is quite unusable on mobile when most of the time as well

**Comment by humphd** [comment]
Two things I noticed this week on mobile:

<img width="341" alt="Screenshot 2024-02-18 at 12 54 12 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/6c87b3a0-096c-4740-b3f0-74bcec88c6e6">

The Audio Recording button isn't the right size

Also, my fix for the wrapping of the placeholder text in the input element is wrong.  On my iOS device, it still wraps.

**Comment by tarasglek** [comment]
@menghif I see that you have a blog. Would you be interested in writing a blog post on why and what you contributed? I'll then do a chatcraft release and link to your blog from release notes

**Comment by menghif** [comment]
@tarasglek great idea, yes I will write a post. Thank you!
