### ISSUE TITLE
Better UX for long messages

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#339]
@tarasglek shared a few chats last night that include really long blocks of text as part of the prompt's context (in both cases, he's asking ChatCraft to create "chain of summaries," which has the LLM iterate on its own work to make it better over time):

- https://chatcraft.org/c/tarasglek/mcHmCrkvVpLKwK7FfjSC2
- https://chatcraft.org/c/tarasglek/oHZpX9u7nHvyK11CGVGHU

Getting to the replies underneath is painful, since you have to scroll a hundred times.  Apps like Discord already provide a way to deal with this in the UI:

![image](https://github.com/tarasglek/chatcraft.org/assets/427398/1bae972d-90f8-4ffd-a1de-4661b457b6ba)

![image](https://github.com/tarasglek/chatcraft.org/assets/427398/11c13b61-2f4a-4af0-abb8-9cda9c583cc4)

When a message or code block is over some threshold in size, we should switch to showing it like a file attachment.  Having some way to open it as text if you need to would be useful too.

**Comment by mingming-ma** [comment]
How about re-use the `Show More...` button when messages are too long and add a new button right to it such as `Download Text`

![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/f0b742b2-681b-4760-9db9-8b340d0984ce)

**Comment by humphd** [comment]
That's a good approach, let's start with that.  Luckily, we already have "Copy" and "Download" implemented:

<img width="272" alt="Screenshot 2024-01-19 at 10 22 12 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/129fda84-8d4a-453c-8386-6e23e9e7b193">

So I guess we need to update the base Message component to truncate the message if its length is over some threshold, and show the "Show More..." button instead.

**Comment by mingming-ma** [comment]
Oh, right! We have the "Copy" and "Download" implemented 😄 I would like to help implement the "Show More..." button

**Comment by tarasglek** [comment]
I like how we do show more in system message. should make sure the 2 are similar i think
