### ISSUE TITLE
TODO: Share/save/project functionality

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#34]
Sometimes I can write whole files using chatcraft. Ideally i'd leave a link to convo that generated them at top of the file.

* Going to that link should restore conversation as it was. perhaps link is a hash of conversation stored in s3?
* convo should also have a human-written description of what the convo is about..gpt could prefill it.
* Restoring basically prefills current msg history
   - should prompt on whether to erase current history?
   - perhaps we should have explicit support for named conversations..where importing a convo would create a new convo "imported blabla" which could be renamed

Another interesting approach is to make a comment that summarizes the prompts needed to recreate the file.  This can be done by deleting all the responses, example:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/857083/235884405-ea1985db-ce9b-446f-857b-383dfd4ad65c.png">
This is cool as it doesn't depend on chatcraft, any gpt implementation could reimplement similar code from such prompts.

**Comment by humphd** [comment]
This is working now:

https://chatcraft.org/humphd/e9d57776-9617-45b6-bf46-24ab6bd437bc

You can try creating one yourself.  Now we can iterate on the UX.
