### ISSUE TITLE
Add back the fixed SOPS decryption method

### ISSUE THREAD

**Issue by Amnish04** [tarasglek/chatcraft.org#350]
PR #348 removed the first method for decrypting sops keys, as it did not work for anyone.
<img width="1204" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/ca94b6b7-6f32-4f0a-927f-1aca657e6a5a">

However, the reason that did not work was that the step where `SOPS_AGE_KEY` environment variable was set did not store the result of the script, but the path of the script file.
https://github.com/tarasglek/chatcraft.org/pull/348#pullrequestreview-1828027901

<img width="842" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/7e24facf-f9f1-4849-9fc5-447d18fac6d1">

That does not mean this method doesn't work. We just need to fix the way we are setting the environment variable such that it has our private age key.

**Comment by humphd** [comment]
Ask ChatCraft to fix that for you...

**Comment by Amnish04** [comment]
> Ask ChatCraft to fix that for you...

Sorry I went rogue 😝

<img width="803" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/1955b731-dd83-40ff-9d6f-c216849470cf">
