### ISSUE TITLE
Add support for openai tts api

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#354]
As a warmup for #310 one can add a tts feature to chatcraft. 
Openai can do tts using really high quality voices: https://platform.openai.com/docs/guides/text-to-speech

We should add a speak menu entry to each message so it can be spoken by these voices. Once the message is spoken, it should also get a download speech menu so we can download the generated speech.

TTS could also allow chatcraft to respond in voice when we ask it questions using the voice feature.

This would be handy for recording voiceovers for demos on youtube, presentations, etc.

**Comment by tarasglek** [comment]
We should also support using browser-local VTT and TTS ala https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

**Comment by Amnish04** [comment]
Sounds Interesting!

I tried to play with it a bit, but for some reason I can't get access the method from documentation
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/c35a3e71-2e62-4d59-bb2d-8213e4367c82)

Am I using the wrong object?
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/1f155d89-3c85-4eea-b11e-97451ef27ddf)
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/5f4b87c4-6b78-48fa-8762-6f81b3ab3309)

**Comment by Amnish04** [comment]
Just found that the version of openai we are using does not support the [speech](https://platform.openai.com/docs/guides/text-to-speech?lang=node) property.

Upgrading to latest fixed it, and I can listen to generated audio.

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/6b9e988c-1c83-4bd2-a3eb-b24dbdef373d)

**Comment by humphd** [comment]
@Amnish04 nice, want to turn your investigation into a PR?

One thing we'd have to do here is make this aware of different providers/models (cc @kliu57).  For example, if I'm using OpenRouter.ai vs. OpenAI for my provider and API Key, this won't work.

To start, maybe we only do this if you're using OpenAI as your provider?

Another thing that would be cool is to allow users to set the voice to use as a setting: https://platform.openai.com/docs/guides/text-to-speech/voice-options

Also, it looks like we can stream it vs. waiting to download: https://platform.openai.com/docs/guides/text-to-speech

**Comment by tarasglek** [comment]
I think the model should show up in list endpoint. Can use that enable disable this feature.


Love how quickly you got an experimental result!

**Comment by humphd** [comment]
> I think the model should show up in list endpoint.

Do you mean in the list of models we show the user, so you an "Ask" or "Retry" with the TTS models?
