### ISSUE TITLE
Show help for unknown command

### ISSUE THREAD

**Issue by Amnish04** [tarasglek/chatcraft.org#356]
I noticed that when a user enters an invalid command, we get the following toast message.

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/e6cee5e3-4e65-4e1c-b6d6-f12af9869d0c)

I found a **TODO** while working on another issue that we need to **handle** this as appropriate for the application.

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/3f4dae1e-8e77-47f2-9674-aba54e11316b)

The regular `/help` command shows a generic list of in guidelines for the app. 

Should we rather only show the commands supported by **ChatCraft** when this happens?

Which would be **this section**:
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/2ae75e96-e0db-47be-9870-e033521c1a16)

**Comment by humphd** [comment]
Sure, it makes sense to show a list of commands.
