### ISSUE TITLE
Use a different Menu component

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#359]
ChakraUI has been amazing, but it lacks a menu component with everything we need.  Specifically, we are in need of sub-menus.

Let's add a new React menu component to our code.  I think https://szhsin.github.io/react-menu looks good, but if people have another idea, I'm open to suggestions. 

I don't want to pull in a whole UI framework, just a menu.

I'd also like to get the default styling of this menu component to match what we have as close as possible, make sure light/dark mode works with our current code, etc.

**Comment by Amnish04** [comment]
I looked up a bit if we just want one component from a different UI library.

https://stackoverflow.com/questions/67940831/importing-only-one-component-from-material-ui

https://www.reddit.com/r/reactjs/comments/wetk5x/is_it_possible_to_import_single_component_from/

They say that [Tree Shaking](https://webpack.js.org/guides/tree-shaking/) would take care of the bundle size, but we would still have to install the entire library, which is not good.

I also like the idea of using [react-menu](https://szhsin.github.io/react-menu).

**Comment by Rachit1313** [comment]
@humphd What about the submenus I previously worked on?
Refer to #343

**Comment by Rachit1313** [comment]
> > @humphd What about the submenus I previously worked on? Refer to #343
> 
> 
> 
> Your work in #343 was useful in helping to understand whether or not ChakraUI's existing Menu could be re-used to create a usable sub-menu.  Testing showed it wasn't, and we really need something that is designed to work in this way.

Okay, Thanks. I'll work towards implementing the react menu and lets see how it comes out?

**Comment by humphd** [comment]
Sounds good @Rachit1313.  Start by getting a new `Menu` component (i.e., `src/components/Menu.tsx`) added to the project that wraps/exposes react-menu.  It should have default styles applied so the colour, fonts, sizing, dark/light mode, etc. all make it appear to be part of the rest of our UI and work similar to ChakraUI.  We might also decide to wrap it in a generic `<Box>` or something in ChakraUI, so we can use style props.

Don't worry about using it at first (other than for testing).  We can replace our existing menus once you have this first part completed.

**Comment by tarasglek** [comment]
Really excited about this!

**Comment by humphd** [comment]
@Rachit1313 we're going to need to see an early version of this in the next day or so in order to get this landed by 1.1 on Friday.

Please focus on getting this integrated for use in 1.2 vs. trying to add it AND use it right away (e.g., you'll likely get stuck of you do that).
