### ISSUE TITLE
Improve visibility of "Share" button for chats

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#362]
Spin-off from https://github.com/tarasglek/chatcraft.org/issues/355#issuecomment-1908580741

We should make it easier to share a chat.  Currently, sharing is available via the chat header menu:

<img width="923" alt="Screenshot 2024-01-24 at 1 34 28 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/a93cdb5b-a939-491a-8555-91b7c75ff132">

This opens the Sharing modal, where users can add/edit/generate a summary, then get a sharable link:

<img width="509" alt="Screenshot 2024-01-24 at 1 35 05 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/277cce6d-04f2-4203-ab7e-76776b64c4a1">

We should [add a Share icon](https://react-icons.github.io/react-icons/search/#q=share) to the prompt area, to make this easier to discover.  It can also open the same modal (e.g., we'd have two ways to do it).

A third way we could explore is using the [Web Share API](https://web.dev/articles/web-share), where you can hook into the OS share UX (e.g., on mobile).  This way would require us to generate the sharable link first.

**Comment by humphd** [comment]
I'm not 100% sure where to add this icon so we don't clutter this:

<img width="904" alt="Screenshot 2024-01-24 at 1 38 25 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/18fd1b55-a2ec-4adb-b297-3167048665d0">

Probably on the right, maybe to the right of the mic?

**Comment by tarasglek** [comment]
or we can just make that whole buttom area a toolbar with lots of stuff :)

**Comment by tarasglek** [comment]
I think we would collapse that toolbar into a menu on mobile.
