### ISSUE TITLE
Investigate bundle size and use more dynamic imports

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#365]
If you run `pnpm build` we generate `stats.html`, which is bundle size info.  Here's what it looks like at the moment:

<img width="630" alt="Screenshot 2024-01-25 at 7 40 10 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/a6e997fe-9427-4c23-bf67-7f07a3c6903f">

I've highlighted a few large modules we should consider [importing dynamically](https://vitejs.dev/guide/features#dynamic-import) vs. statically.  We've already done this for a few large modules, see https://github.com/search?q=repo%3Atarasglek%2Fchatcraft.org%20await%20import&type=code.

The modules highlighted above are for features of Mermaid diagrams and Katex math rendering.  Both of these are used in special cases, so we should consider loading the modules only when needed vs. every time.

**Comment by tarasglek** [comment]
love this...would also love to produce this as asset in github actions

**Comment by humphd** [comment]
Sure, we could put this `stats.html` page + Vite test coverage HTML on GitHub Pages or something.

**Comment by rjwignar** [comment]
When attempting to fix this I identified three large modules for dynamic importing:
1. **elkjs** (for Mermaid)
2. **cytoscape** (for Mermaid)
3. **katex** (for Math rendering)

The **elkjs** and **cytoscape** modules are _both_ dependencies of **mermaid**:

The **katex** module is a dependecncy of **two modules**:
- **rehype-katex**:
- and **micromark-extension-math** (not directly imported in code):
...which itself is a dependency of **remark-math** (directly imported in code)

Full explanation available at https://github.com/tarasglek/chatcraft.org/pull/472

My findings:
- **elkjs** and **cytoscape** can't be feasibly dynamically imported. At least with what I've tried, these can only be dynamically imported if mermaid is dynamically imported, but the mermaid package is always required., so it's not useful to dynamically import this. If there is a way to somehow dynamically import these dependencies from within mermaid

- I tried dynamically importing the **rehype-katex** and **remark-math** packages in #472. These changes seem to work locally, but when deployed on the [preview](https://rjwignar-issue-365.console-overthinker-dev.pages.dev/) but there is a workbox-related issue preventing the app from loading. This can be revisited in the future if we can figure out the workbox-related issue.
