### ISSUE TITLE
Don't encode & in Markdown for URLs

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#373]
In #370 I'm trying to create URLs in Markdown to YouTube that have time codes.  The URL includes things like `&t=1m30s`.  Our Markdown rendering code is converting that to `&amp;t=1m30s`, which breaks the URL.

**Comment by mingming-ma** [comment]
OMG, I got the solution from the remarkjs maintainer and it is pretty simple:

[How to prevent '&' from being converted to '\&amp;' in a URL?](https://github.com/orgs/remarkjs/discussions/1286)

> run `npm update`

I tested on my local env and it works. 

![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/979a4444-f799-4ccd-bcd8-3e93e625b6ff)

@humphd How can we update properly on the Cloudflare env ?

**Comment by humphd** [comment]
Neat: https://github.com/remarkjs/react-markdown/commit/d8e37874915b79a2ee20ec2944793ef5ca7a2379

Update the dep in `package.json`.
