### ISSUE TITLE
Support running severside deno via val.town eval api

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#384]
They offer a public eval endpoint. This is a good first step towards further integration.

Some examples:
```bash
curl -X POST https://api.val.town/v1/eval -H "Content-Type: application/json" -d '{"code":"async () => (await fetch(\"https://google.com\")).text()", "args":[]}'
```
```bash
curl -X POST https://api.val.town/v1/eval -H 'Content-Type: application/json' -d '{"code":"async() =>(Math.sqrt(1 + 3))", "args":[]}'
```

https://chatcraft.org/c/tarasglek/EO7koh0tZBBEdnJPR5Jf6

Idea is that in addition to run button for js, we also have a way to choose whether it runs serverside or clientside...When running serverside, we package up any code into an async anon function and POST it to api

I would like this to be a start of functionality of supporting valtown as a way to do custom /import-like stuff

**Comment by humphd** [comment]
https://www.val.town/ for those not familiar.
