### ISSUE TITLE
Allow language conversions for code blocks

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#397]
Lots of languages or data formats can be automatically converted and become easier to use.  Consider:

- JSON to YAML
- CSV to HTML or JSON
- TypeScript to JavaScript

It would be cool if you had an easy way in the UI to convert code blocks to other supported languages.

I did an experiment with this using JSON to YAML.  It's kind of tricky to get the React rendering right, the way our Markdown and SyntaxHighlighting works (I think it would require a new Context).

However, I paused before doing all this work, since it became unclear to me whether the feature would be what people expect.

When we convert the data, we're really just altering the way we render it: underneath the original data still remains.  Is that good enough?  For example, what the LLM sees in future messages would not be what you see.  I wonder if this defeats the purpose.

**Comment by WangGithub0** [comment]
Dave says we are not going to do this.
