### ISSUE TITLE
Fixing the unusual scroll bar 

### ISSUE THREAD

**Issue by Rachit1313** [tarasglek/chatcraft.org#398]
Based on @Amnish04 's comment, I confirm that after deploying I can see the unusual scroll bar triggered when opening menu
Refer #374 
<img width="1429" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/a517257b-fa08-473a-90ab-4a74f16e8461">

**Comment by humphd** [comment]
Which browser/OS are you using?  Is it due to the sidebar being open?

**Comment by humphd** [comment]
Interesting.  Bugs like this can be subtle, and finding the right set of steps to reproduce it, tricky.  I'm not able to reproduce this on macOS/Chrome, but that doesn't mean it's not there.  See if you can figure out what you're doing that I'm not.

It could be related to the content you're using in the chat, for example, or somehow be caused by an extension, etc.

**Comment by rjwignar** [comment]
@Rachit1313 what size is your screen/monitor?

I'm on Windows 10/Edge I don't encounter the bug when I open the menu on a maximized ChatCraft window (on a **27-inch monitor**), even with the sidebar open:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/79f6f80e-1845-4655-90f0-c22ad87a06d2)

For me, the horizontal bar will appear when I reduce the ChatCraft window to a certain screen width.
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/af57dbd6-fb37-4196-bb26-fd6573ffb5c2)

**Comment by Rachit1313** [comment]
<img width="1440" alt="Screenshot 2024-02-04 at 1 00 40 PM" src="https://github.com/tarasglek/chatcraft.org/assets/58596563/2097e0b4-56a4-48d4-84b8-1a4774157b7a">
I can even see this right now 100% width on 13 inch macbook pro

**Comment by humphd** [comment]
Whatever is causing it, the issue is that we have an `overflow-x` on a parent element that shouldn't have it.  Do you want to see which one it is?
