### ISSUE TITLE
multiple chat threads

### ISSUE THREAD

**Issue by steven4354** [tarasglek/chatcraft.org#40]
been using chatcraft! its great over chatGPT esp with the gpt4 limits on chatGPT. 

it'd be great if there was a way to have multiple threads going with the chat (instead of only 1 chat at a time like chatGPT)

**Comment by humphd** [comment]
This is connected to #13.

**Comment by tarasglek** [comment]
what are the gpt4 limits on chatgpt?

**Comment by steven4354** [comment]
currently is it 25 gpt4 messages max every 3 hours

**Comment by humphd** [comment]
I think has been solved with new db backend: you can have as many parallel chats going as you want now.  @steven4354, I'm going to close this, but please re-open or file again if I've misunderstood.
