### ISSUE TITLE
Learn from Prompt Builder UI

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#405]
https://mitenmit.github.io/gpt/ is a very creative approach to guiding people through building a (system) prompt.  I wonder if we could learn from and incorporate these ideas, maybe with a "guided" mode

**Comment by tarasglek** [comment]
We should hook up https://clarity.microsoft.com/?sr=1 to track how users use chatcraft first.

**Comment by humphd** [comment]
> We should hook up https://clarity.microsoft.com/?sr=1 to track how users use chatcraft first.

Filed #409
