### ISSUE TITLE
option to "cancel" a generation

### ISSUE THREAD

**Issue by steven4354** [tarasglek/chatcraft.org#41]
would be great if there is a way to "cancel" a generation next to the "loading ..." button when i don't need more generations for the current answer

**Comment by humphd** [comment]
This should be doable now with https://js.langchain.com/docs/modules/models/llms/additional_functionality#cancelling-requests.  I think @tarasglek tried to do it before and their implementation had bugs.

I want this too.

**Comment by humphd** [comment]
@steven4354 I made a PR you can test in #43.  There's a preview URL to test it at https://6c0ec221.console-overthinker-dev.pages.dev/

**Comment by steven4354** [comment]
ooo nice! its working!

https://capture.dropbox.com/jAC7r55cRSSRCtQO
