### ISSUE TITLE
Math formula plotting

### ISSUE THREAD

**Issue by kosty** [tarasglek/chatcraft.org#415]
While I do not have a clear proposal on technical solution to this, it would be super helpful if any latex expression provided by LLM could be also visually represented with a corresponding graph. 

Currently LLM tried to paint it using Mermaid (as instructed)
<img width="929" alt="Screenshot 2024-02-06 at 10 34 02 PM" src="https://github.com/tarasglek/chatcraft.org/assets/630193/9994c7ef-9f86-4af4-8d29-6ee4deb89cad">

potentially things like https://mathjs.org/examples/browser/plot.html (i guess they are using [Plotly.js](https://plotly.com/javascript/)

Or find some online plotter that works similarly to latex.codecogs.com. Wolfram Alpha?

**Comment by Rachit1313** [comment]
Hi @kosty ,
I believe you can approach this using another way asking chatcraft to create a HTML page using plotly.js 
https://2ff43a23.console-overthinker-dev.pages.dev/c/chatcraft_dev/qZHUoM15LG68Pp4tsytpA
