### ISSUE TITLE
ability to "fork" a chat thread

### ISSUE THREAD

**Issue by steven4354** [tarasglek/chatcraft.org#42]
would be amazing if I could take an existing chat thread and then fork and duplicate it into a new thread so I can continue off coding a different section of an app

e.g. 

here's the codebase ...

fork1 -> code the database migrations for me
fork2 -> code the frontend for me
fork3 -> fix this bug for me

and have them all running at the same time

**Comment by humphd** [comment]
Somewhat similar to #34.

Can you share more about your use case above?  I'm trying to understand what this would look like.

So you have a base thread, where you've described your project, and the 3 forks take the base info into different areas of the code?

**Comment by steven4354** [comment]
yep #34 would be super similar actually
