### ISSUE TITLE
Refactor settings API URL dropdown to read from list of ChatCraftProvider

### ISSUE THREAD

**Issue by kliu57** [tarasglek/chatcraft.org#423]
Now that we have the ChatCraftProvider class,

In Settings:

API URL dropdown contents should be a list ChatCraftProvider objects

---

This issue originates from:

-  This comment in Issue#345: [The UI in the settings would change to iterate over the list of providers, and show the various fields for each (i.e., show the Name, URL, API Key for each).](https://github.com/tarasglek/chatcraft.org/issues/345#issuecomment-1909001948)
- Also see [this](https://github.com/tarasglek/chatcraft.org/pull/371#issuecomment-1912969306) comment in PR371 and [this](https://github.com/tarasglek/chatcraft.org/pull/371#issuecomment-1913167443)

**Comment by kliu57** [comment]
@humphd if I were to create a list of `ChatCraftProvider`s we currently support, in which file should I store that list?

**Comment by kliu57** [comment]
@humphd how about storing it in [settings.js](https://github.com/tarasglek/chatcraft.org/blob/main/src/lib/settings.ts)? 

![image](https://github.com/tarasglek/chatcraft.org/assets/98062538/144404f4-6b46-4adf-adf4-f91c7351879f)

**Comment by humphd** [comment]
It's not really a setting, it's more a static array that's part of our code.

Can you put it in `ChatCraftProvider.ts` and export it as `supportedProviders = [...]`?
