### ISSUE TITLE
Store attachments as Blob type

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#426]
In #281 we are adding initial support for attachments.  Currently, we only support `image/*` files, but in #325 we are going to expand this to allow more types.

The way we're handling current image attachments is closely linked to OpenAI's requirements for base64 image URIs, since that's where this feature was first needed.  However, this isn't a great approach, and using a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) is a much better  approach.

Let's alter the way we store and manage attachments in the db and throughout our code to use `Blob`s, which can be generic and work with any type.  We should probably also add a new class, `ChatCraftAttachment` or `ChatCraftFile`, etc. which can handle various conversions (e.g., file -> base64String).

**Comment by rjwignar** [comment]
@rjwignar tagging myself for awareness

**Comment by humphd** [comment]
I suspect we'll move to a more "Assistants" style db in the near future, so I'm going to close this.
