### ISSUE TITLE
Add twitter card metadata

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#432]
Silly twitter doesn't render OG in our shared chats, eg https://chatcraft.org/api/share/tarasglek/5szbfO7gPyjwQLzJE96wb

Need to add twitter-specific cards mentioned in https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

**Comment by rjwignar** [comment]
@tarasglek Can you help me understand the issue?

I've looked at the chat and I don't see any embedded tweet:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/ca9cc800-777f-4898-aa1c-b0ae887af78b)

> Silly twitter doesn't render OG in our shared chats, eg

What does the original chat look like?

**Comment by humphd** [comment]
@rjwignar he means that Twitter won't use OpenGraph data to render a share.  Here is what we have in the head of the shared chat:

```html
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Web-based AI Assistant for Software Developers" />
    <meta name="og:site_name" content="chatcraft.org" />
    <meta property="og:image" content="https://chatcraft.org/favicon-32x32.png" />
    <meta property="og:url" content="https://chatcraft.org" />
    <meta property="og:title" content="chatcraft.org" />
    <meta property="og:description" content="Web-based AI Assistant for Software Developers" />
    <link rel="apple-touch-icon" sizes="180x180" href="[/apple-touch-icon.png](https://chatcraft.org/apple-touch-icon.png)" />
    <link rel="icon" type="image/png" sizes="32x32" href="[/favicon-32x32.png](https://chatcraft.org/favicon-32x32.png)" />
    <link rel="icon" type="image/png" sizes="16x16" href="[/favicon-16x16.png](https://chatcraft.org/favicon-16x16.png)" />
    <meta name="theme-color" content="#ffffff" />
    <title>ChatCraft</title>
```

To fix this, we need to add Twitter Card meta tags as well: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

You can use the Twitter Card validator to test a URL: https://cards-dev.twitter.com/validator

**Comment by tarasglek** [comment]
But the idea of rendering OG inside chatcraft is interesting . We could offer that for when urls are present and offer a "scrape" link to make our scrape functionality more discoverable
