### ISSUE TITLE
Page Moves Up When Clicking Saved Chat

### ISSUE THREAD

**Issue by rjwignar** [tarasglek/chatcraft.org#442]
## Issue

Today, I've noticed the ChatCraft window moves up when I access saved chats:
![scrollbar issue](https://github.com/tarasglek/chatcraft.org/assets/78163326/52f5491f-8fca-497a-9526-8a8e1c40c005)

The effect increases if I click on an older Chat (lower in the list).

Is anyone else experiencing this issue?

## System Information
Issue was encountered opening ChatCraft on Microsoft Edge on Windows 10

## How to Reproduce

1. Navigate to https://chatcraft.org.
2. Open Saved Chats drawer
3. Open a Chat from the bottom of the list

**Comment by humphd** [comment]
@Amnish04 fixed this before, I wonder how we broke it again?

**Comment by Amnish04** [comment]
@humphd Seems to be happening after #431

**Comment by rjwignar** [comment]
@humphd @Amnish04 The last time this happened, did it also affect Shared Chats and the Searchbar?
I'm also seeing issues accessing Shared Chats:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/d11c8551-2771-4df1-a0f4-3826ce10501d)

and when using the search bar:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/a0411680-40d5-43cd-84e5-69bcd95ac948)

**Comment by Amnish04** [comment]
@rjwignar  I don't these errors are related to the UI bug. But it also seems to be happening after #431 as per my experiments

**Comment by rjwignar** [comment]
I'll file followup issues for both
