### ISSUE TITLE
Don't show Delete sub-menu if there's only 1 option

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#444]
Sometimes you can delete messages before and/or after the current one.  Sometimes you can only delete the current one.

When you can only delete the current one, there's no point doing a sub-menu, and it should just be Delete on its own as a menu item.

<img width="1064" alt="Screenshot 2024-02-12 at 9 03 05 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/a5bbe6c4-5647-4955-bf32-c4347974c133">

**Comment by Rachit1313** [comment]
@WangGithub0 , Can I work on this one if you didn't start yet?
