### ISSUE TITLE
Inline KaTeX Rendering 

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#460]
This message renders partially correct, but the inline bits in the first sentence don't work.  I wonder if we could update our default prompt so they do?

```
To convert bytes to megabytes (MB), you can divide the number of bytes by \(2^{20}\) (since 1 MB is \(2^{20}\) bytes or 1,048,576 bytes).

Given the number of bytes as 20,971,520:

$$\frac{20,971,520 \text{ bytes}}{2^{20}} = \frac{20,971,520}{1,048,576} = 20 \text{ MB}$$

So, 20,971,520 bytes is equal to 20 MB.
```

<img width="909" alt="Screenshot 2024-02-15 at 9 44 55 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/0581eff5-0ddc-46aa-9453-02ca0aa728cd">

**Comment by rjwignar** [comment]
@humphd is the output provided generated by the LLM?
If so, what initial message did you provide?
I have a fix in mind, but I'm not sure how to reliably coach ChatCraft into giving me in-line KaTeX
