### ISSUE TITLE
Add loading indicator for the image compression

### ISSUE THREAD

**Issue by mingming-ma** [tarasglek/chatcraft.org#467]
Would be helpful for user to know the process

Something like [Gimini ](https://gemini.google.com/app) does

![image](https://github.com/tarasglek/chatcraft.org/assets/133393905/e1a7c886-4ab8-4fd6-87f2-5f6abeaa97c2)

**Comment by humphd** [comment]
We already have that on the ask button, how is this different?

**Comment by mingming-ma** [comment]
Just checked that one, its a prop `isLoading` of `Button` component. It depends on how to implement this on the image placeholder,  maybe [spinner](https://chakra-ui.com/docs/components/spinner) also good to choose.
