### ISSUE TITLE
mermaid does not work with images

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#47]
"diagram of chatcraft.org(include favicon https://chatcraft.org/favicon-32x32.png) being hosted on cloudflare pages and talking to gpt api via langchain"

<img width="668" alt="image" src="https://user-images.githubusercontent.com/857083/237036579-eb411266-1345-4b14-919b-3a73014a62b7.png">

**Comment by humphd** [comment]
I don't think this is a bug we can fix.  Re-open if something new happens with upstream Mermaid support.
