### ISSUE TITLE
Fix image generated not available after some time

### ISSUE THREAD

**Issue by mingming-ma** [tarasglek/chatcraft.org#496]
The image generated will be not available due to URL lifetime ( #493 )

<img width="227" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/133393905/b344a8de-2ff9-4a54-9e0f-944a5d2caf04">

Need to figure out how to store so user can back check them later.

[DALL-E API Image URL lifetime](https://community.openai.com/t/dall-e-api-image-url-lifetime/53672)

**Comment by rjwignar** [comment]
I ran into this issue while working on a class project.
We ended up using [Cloudinary](https://cloudinary.com/)'s free tier to store DALL-E-generated images, but
a better solution for ChatCraft might be to use a local object storage instance.

@humphd we're already using R2 to store local chats, would it be a good idea to store these images in R2 as well?

**Comment by humphd** [comment]
For shared chats, yes.  For local ones, they will be in db.

**Comment by mingming-ma** [comment]
so a possible fix maybe, don't know fetch again in the response is a good idea
```ts

    const imageDataUrls = await Promise.all(response.data.map(async (img: any) => {
      const imageResponse = await fetch(img.url);
      const imageBlob = await imageResponse.blob();
      const imageDataUrl = URL.createObjectURL(imageBlob);
      return imageDataUrl;
    }));

```
