### ISSUE TITLE
Chatcraft commands conflict with code errors

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#500]
parsting below block
```
/workspaces/DeepStructure/misc/getsetup/add-to-notion.ts:181
        throw new Error(`Notion API call failed: ${await response.text()}`);
              ^


Error: Notion API call failed: {"object":"error","status":400,"code":"validation_error","message":"body failed validation: body.children[0].heading_1.rich_text should be defined, instead was `undefined`.","request_id":"f73a1254-1204-4610-9820-76f6890821dc"}
    at notionApiCall (/workspaces/DeepStructure/misc/getsetup/add-to-notion.ts:181:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createHeadingWithText (/workspaces/DeepStructure/misc/getsetup/add-to-notion.ts:137:5)
    at updateOrAppendAiSummary (/workspaces/DeepStructure/misc/getsetup/add-to-notion.ts:113:5)
    at main (/workspaces/DeepStructure/misc/getsetup/add-to-notion.ts:192:5)

Node.js v20.8.1
```
causes chatcraft to just spin the loading icon. We should probably not assume all /things are commands

**Comment by rjwignar** [comment]
You're right. The filepath provided in the error passes the initial check for a suspect slash command:
https://github.com/tarasglek/chatcraft.org/blob/f7b28038b3820d617a14b346536377977f4379d0/src/lib/ChatCraftCommand.ts#L19-L21.
Downstream, ChatBase interprets this as an unknown slash command then tries to parse it for the "[command] is not a valid command!" message:
https://github.com/tarasglek/chatcraft.org/blob/f7b28038b3820d617a14b346536377977f4379d0/src/Chat/ChatBase.tsx#L247-L253

The filepath contains non-word characters (`/`) after the initial forward slash, so parseCommand returns null and :
https://github.com/tarasglek/chatcraft.org/blob/f7b28038b3820d617a14b346536377977f4379d0/src/lib/ChatCraftCommand.ts#L10-L12

Then line 253 of ChatBase throws this error:
![image](https://github.com/tarasglek/chatcraft.org/assets/78163326/197d1d6e-8bb7-4911-9544-cc423b9be3ed)
