### ISSUE TITLE
Update on-boarding flow with new Free AI Models provider

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#501]
With the work in #498 that @kliu57 has done, we need to rethink our on-boarding flow.  Previously, you needed an API Key in order to do anything.  Now, we have a "free tier" that users can use if they don't have a key.

We should think about how to leverage this.  A few options:

1. Default to the free tier and provide some kind of UI decoration that lets the user know that they can add their own API key for more features
2. Update our "instructions" so that the user can easily click a big button to start using the free models if they don't have/don't want to enter a key

**Comment by tarasglek** [comment]
1. Is good

**Comment by kliu57** [comment]
I can do this but what kind of UI decoration do we want? Would need to see a rough design or rough idea.

**Comment by humphd** [comment]
This is a great question. I'm not 100% sure of the right solution.  Some thoughts:

- We could do it on the header for the app, up beside the login/settings, and it could be a colourful button
- We could do it in the prompt area
- We could add it to the model selector in the prompt area, so when you go to change models, it has "Add your own API Key..." or something
- We could add some text/button to the end of each response from the model saying it.

We should try to find some examples of apps that already to this.

**Comment by tarasglek** [comment]
I like this UX
![image](https://github.com/tarasglek/chatcraft.org/assets/857083/c19c86fc-b1ab-4581-9530-067503590b34)

"You are limited to free AI models from openrouter.com. Obtain a paid account from openai.com or openrouter.com for better results"

should have [x] button to dismiss the free banner

**Comment by humphd** [comment]
Nice.  That would be pretty easy to do with https://chakra-ui.com/docs/components/alert/usage as part of the header itself (e.g., append it below).

**Comment by humphd** [comment]
For working in the header, how about this:

> You are using the default free AI Provider, which has limited features. Click here to add other AI providers
