### ISSUE TITLE
Better images preview behaviour

### ISSUE THREAD

**Issue by mingming-ma** [tarasglek/chatcraft.org#505]
As discussed in https://github.com/tarasglek/chatcraft.org/pull/493#issuecomment-2000252215, we   could use better lib such as [react-medium-image-zoom](https://www.npmjs.com/package/react-medium-image-zoom) to get enhanced images preview vs the image modal popup.

**Comment by Amnish04** [comment]
I was actually thinking of having the click and zoom feature inside the modal instead of completely removing the modal.
Reason being, the modal allows the user to look at the entire image in a single frame. My proposal is to extend that behaviour so users have more flexibility in preview

**Comment by mingming-ma** [comment]
@Amnish04 My bad, just saw the transparent background and images zoom from it's original size is great!  
if we keep using the modal, do you mean we implement similar behaviour, e.g. the modal zoomed ? (I know we should change the cursor at the first step)

**Comment by Amnish04** [comment]
@mingming-ma I was thinking of allowing the user to zoom in and zoom out the image in the image preview modal itself.

I am not sure if what I've shared is the best library for our purpose, so I am looking for more

**Comment by Amnish04** [comment]
@mingming-ma I was experimenting with [react-zoom-pan-pinch](https://bettertyped.github.io/react-zoom-pan-pinch/?path=/story/docs-introduction--page) and it gives me this for starters.

![ZoomPinchPanDemo](https://github.com/tarasglek/chatcraft.org/assets/78865303/834bbdea-cfa9-49b6-aa3a-96d82db40a40)

I think this one should be good for our needs as it supports mobile gestures as well.

My proposal:

1. Let's have a **zoom-in cursor** on an unzoomed image when the modal opens.
2. When a user clicks on the image, we should zoom it to a certain scale and allows the user to reposition the image center with drag/swipe like in my gif.
3. When in zoomed state, the image should have a cursor of **zoom-out**.
4. If the user clicks it again (in zoomed state), we should unzoom it, i.e. scale = 1

**Comment by mingming-ma** [comment]
@Amnish04 I think it's great to ship this! Can you make a PR when you're satisfied ?

**Comment by Amnish04** [comment]
@humphd suggested in today's triage that we can rather open the image in a new tab rather than implementing zoom and pulling a new library
