### ISSUE TITLE
Make it easier to switch between providers

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#510]
Currently, we assume that the user only ever wants to use a single provider. For example, the "Ask" menu shows models for the current provider:

<img width="1009" alt="Screenshot 2024-03-17 at 5 22 20 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/4951e561-c1bc-41f3-8457-8b18b4999abb">

However, @kliu57 has been doing awesome work to add support for multiple providers.  Now that we support 3 providers, and soon arbitrary providers (see #440), it would be interesting if the "Ask" menu allowed you to easily switch to another of your configured providers and use those models.

I wonder if this would be a good UX:

```
+--------------+
| model-1      |
| model-2      |
| ...          |
|--------------|
| ✔️ Provider 1 |
|   Provider 2 |
|   Provider 3 |
+--------------+
Ask
```

In the wireframe above, the models for the current provider (i.e., "Provider 1") are shown.  In addition, the other providers are also available, and clicking on "Provider 2" or "Provider 3" would cause the list of models to change.

There might be a better UX for this, but that's one option.

**Comment by kliu57** [comment]
Only show providers which has keys in this list (providers saved in settings.supportedProviders array)

**Comment by Amnish04** [comment]
UX Suggestion
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/1371986f-e161-4c35-8988-649565b826a3)
