### ISSUE TITLE
Keyboard shortcut to focus the input bar

### ISSUE THREAD

**Issue by chadparker** [tarasglek/chatcraft.org#511]
Is there no keyboard shortcut to focus the input bar? I find myself wishing for this all the time, and I'm surprised that a tool meant for programmers doesn't have it.

Other sites that DO have such keyboard shortcut:

- Perplexity: `Cmd-/`
- Phind: `/`
- Google search: `/`
- Gmail: `/`
- YouTube: `/`
- Jira: `/`
- Github: `/`

Others don't have it and it drives me mad: Google Gemini, (wow, many sites have it!)

Anyways, this is obviously becoming a pattern on the web and I think ChatCraft should implement it as well. I'm not a web developer so I'm not sure how to do this, otherwise I'd make a PR for it.

**Comment by humphd** [comment]
Thanks for filing this @chadparker, I think it sounds like a great idea.  This might be something that one of my students wants to take.

**Comment by rjwignar** [comment]
I'd like to try this out.
