### ISSUE TITLE
Models format wrong for https://www.val.town/v/taras/free_open_router

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#515]
The OpenAI client code can't parse the models response for https://platform.openai.com/docs/api-reference/models/list.  @tarasglek can you fix it to match https://platform.openai.com/docs/api-reference/models/list?  I think it's just missing `"object": "list"`.

cc @kliu57

**Comment by tarasglek** [comment]
does openrouter have this @kliu57

**Comment by tarasglek** [comment]
(I verified that openrouter also doesn't return this response)

**Comment by tarasglek** [comment]
We might need to use a fetch() adapter to inject it on clientside, cos i bet most open source list endpoint wont work too

**Comment by kliu57** [comment]
@tarasglek I was bebugging this with Dave and Dave thinks it's due to the content type being wrong, everything else is the same as OpenRouter. Try to return JSON for the content type?

**Comment by humphd** [comment]
I don't think this is still an issue.  Please file again if I'm wrong.
