### ISSUE TITLE
Don't hide previews (HTML, Mermaid) in old messages while replying

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#52]
Follow-up from https://github.com/tarasglek/chatcraft.org/pull/48#issuecomment-1541603409:

>  it hides all mermaids during reply. I think it should only hide the in-progress one, my original code did that.

The `Markdown` component is only showing previews when the `previewCode` prop is passed in.  We did this to reduce flicker/crashing when previews might crash (they won't now) and to deal with re-renders of the messages.  We should make the previews stick around once rendered, and not re-render old messages.

**Comment by tarasglek** [comment]
The new prompt made model less likely to draw stuff.
<img width="861" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/4145aa4d-f6a3-40c3-b212-12da726576df">

**Comment by humphd** [comment]
This is fixed.  I removed prompt change in `streaming-buttons` branch, so file a new issue if you want to iterate on the prompt stuff.
