### ISSUE TITLE
Advanced Image Compression settings should be hidden by default

### ISSUE THREAD

**Issue by Amnish04** [tarasglek/chatcraft.org#522]
#513 added settings in Preferences Modal for configuring image compression.

This makes the modal too long.
<img width="657" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/99214532-9d0d-430b-8307-7a92badb4103">

We should have those settings in an **Expansion Bar** so the user can reveal those settings if needed

**Comment by Amnish04** [comment]
This would also eliminate the need to rely on `fieldset` and weird alignment since the grouping would be handled by an **Accordion**

https://chakra-ui.com/docs/components/accordion/usage

**Comment by menghif** [comment]
Can I be assigned to this?

**Comment by humphd** [comment]
Done!

@tarasglek would you please invite @menghif to the repo so he can do preview branches?

@menghif when you get your invite, please do all your branches on this repo vs. your fork using `menghif/*` for the branch name.  Then we get preview deployments on CloudFlare for every PR.

**Comment by Amnish04** [comment]
@humphd I remember this issue was opened with you not liking how long the modal has become.

Its is not directly related this issue, but we can also change the modal overflow to `inside` and fix its height to whatever looks best to us.

https://v2.chakra-ui.com/docs/components/modal/usage#modal-overflow-behavior

But I don't know if you like the scrollbar that would appear right next to modal body.

**Comment by humphd** [comment]
@menghif we have another set of issues about redoing the entire settings modal, that you might want to help with as well.  That's kind of the right place to fix this; though I'd take a small fix just for this, too.

**Comment by tarasglek** [comment]
@menghif please accept invite, looking forward to this

**Comment by menghif** [comment]
> @menghif we have another set of issues about redoing the entire settings modal, that you might want to help with as well. That's kind of the right place to fix this; though I'd take a small fix just for this, too.

I'll send a fix for this one but I can definitely help with the new setting modal if needed!

**Comment by humphd** [comment]
I suspect that @kliu57, @Amnish04, and others would appreciate help with the new modal; but I'll get them to confirm that I'm right and they aren't already working on it.

**Comment by kliu57** [comment]
No one has started work on the new modal yet. @menghif I can assign it you if you're interested. Issue #578 . You can click on the associated issue to see mockup UI.

**Comment by menghif** [comment]
@kliu57 Sure I can take it.

**Comment by menghif** [comment]
Closing this since the new Settings layout just landed. https://github.com/tarasglek/chatcraft.org/pull/592
