### ISSUE TITLE
TTS throws error when more than 4096 characters

### ISSUE THREAD

**Issue by Amnish04** [tarasglek/chatcraft.org#525]
I realized that Text to Speech only allows 4096 characters at max. @tarasglek also mentioned it before

<img width="566" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/78865303/ab587e55-32d7-459a-83d7-4385e341b5b5">

Not sure what's the best way to handle this. 
Should we hide the TTS options when the message is too long or let the error show as its current state?

I think hiding the options can be confusing for users.

**Comment by Amnish04** [comment]
@Rachit1313 Can I move this issue https://github.com/tarasglek/chatcraft.org/issues/525 to next release.

That issue might be a little time consuming, and my next week is lighter than this one.

Instead, I can take this issue https://github.com/tarasglek/chatcraft.org/issues/541 that I was originally planning to do in next release

**Comment by Rachit1313** [comment]
> @Rachit1313 Can I move this issue https://github.com/tarasglek/chatcraft.org/issues/525 to next release.
> 
> 
> 
> That issue might be a little time consuming, and my next week is lighter than this one.
> 
> 
> 
> Instead, I can take this issue https://github.com/tarasglek/chatcraft.org/issues/541 that I was originally planning to do in next release

sure, Go ahead.
