### ISSUE TITLE
Try to find other package to parse HTML on cloudflare

### ISSUE THREAD

**Issue by WangGithub0** [tarasglek/chatcraft.org#532]
In this [PR](https://github.com/tarasglek/chatcraft.org/pull/512), using cheerio to parse HTML on cloudflare, but it was published 2 years ago and hasn't seen updates since that. 
Try to find a better one.

**Comment by tarasglek** [comment]
I use linkedom in https://www.val.town/v/taras/markdown_download

**Comment by humphd** [comment]
I think `linkedom` will fail in Workers without access to `document`.

**Comment by tarasglek** [comment]
what do you mean, it works fine in my cf worker

**Comment by humphd** [comment]
Ah, cool.  I'm wrong then
