### ISSUE TITLE
Don't show "free mode" banner when multiple providers are set

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#544]
We show a "You are using the free model..." banner when the user first comes to ChatCraft and we want to let them know about adding more providers for better features.

However, even after you add an OpenAI or OpenRouter provider, when you switch back to the free provider, we show the banner again.

Let's improve our check for the free provider banner so that it looks to see if the free provider is the *only* provider you have configured.  If you have more than one, don't show it.

**Comment by rjwignar** [comment]
I tried fixing this a month ago and I was stumped.
After looking at it again I think I know what to do.
I'll have something tonight or tomorrow
