### ISSUE TITLE
Support for 32k GPT4

### ISSUE THREAD

**Issue by steven4354** [tarasglek/chatcraft.org#55]
Might not be something that you guys can support rn, but thought I'd throw up a ticket

If you have a gpt4 32k api key, i'd pay chatcraft to be able to access it (e.g. proxying the calls to chatcraft etc). This might require charging the users money however.

I currently don't have access to the 32k version of gpt4 but would be interested in being able to use it (via chatcraft)

**Comment by humphd** [comment]
I don't have access either (I tried, but can only get "GPT-4").  Maybe @tarasglek has some other magical API key?

**Comment by tarasglek** [comment]
I'm just a regular gpt-4 
<img width="209" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/2908f06f-8937-4452-998b-73ea76fffcad">
