### ISSUE TITLE
PasswordInput component refactor

### ISSUE THREAD

**Issue by kliu57** [tarasglek/chatcraft.org#553]
For discussion

Right now we are taking a single inputSize param in `PasswordInput` component.

When it is "sm", then we make the padding/sizes/colors to match the small password input field that we currently use in the providers table.

When the param is not specified, we make the padding/sizes/color to match our regular password input field we use in instructions page.

Proposed by @Amnish04 that instead of hardcoding all the prop values like size, padding, color, etc, that we all all those props to the PasswordInput component so that it can be dynamically altered.

**Comment by Amnish04** [comment]
Associated Discussion --> https://github.com/tarasglek/chatcraft.org/pull/530#discussion_r1550268312
