### ISSUE TITLE
Feed icon should open raw feed

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#572]
I find it surprising that clicking the new "Feed" button copies the feed URL to your clipboard vs. opening that in a new tab:

<img width="749" alt="Screenshot 2024-04-07 at 2 14 22 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/61fc1cdf-8f18-4508-aa35-abef959924e7">

I think this should be an `<a target="_blank">...` that simply opens it for you.

**Comment by Amnish04** [comment]
I also noticed that in existing code, the error message when user is not logged is not accurate
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/41ec2898-bd8f-4b0b-8162-5ccda22b62f3)
