### ISSUE TITLE
Create Two-Column Modal component

### ISSUE THREAD

**Issue by kliu57** [tarasglek/chatcraft.org#578]
Create two column modal component as a precursor to implementing https://github.com/tarasglek/chatcraft.org/issues/561

**Comment by humphd** [comment]
For comparison, here's how Slack's version of this modal looks:

<img width="803" alt="Screenshot 2024-04-11 at 8 54 36 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/eddd5b86-0fd9-4d32-9959-670aafc6af12">
