### ISSUE TITLE
Add indicator of what model responded to message and menu to try response with a different model

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#59]
For example..at bottom of message add greyed out "response by chatgpt-3.5" with a little menu, that has buttons to "retry with gpt-4/claude/etc". This would also in the future support the full set of params eg temperature, prompt, etc. Maybe this would tie in with threads(https://github.com/tarasglek/chatcraft.org/issues/40), receipts(https://github.com/tarasglek/chatcraft.org/issues/61)

This would make it easy to compare models plus their params via "retry with gpt4", make for some good blog posts.

One potential UI like..is clicking on the "response by chatgpt-3.5" would open sidebar where we can tweak prompt, model, etc and click retry

**Comment by humphd** [comment]
I think we have the pieces in place to explore this more easily now.  Consider:

<img width="923" alt="Screenshot 2023-06-01 at 9 31 37 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/b16006ef-6a58-414f-afac-bd370022bb40">

We could put a "gear" icon or something near the date or name of model, and it could open an accordion showing a form with model params used to generate it.  It could also include a "Retry" button.

Or we could integrate this into the "dots" menu on the right somehow.

Let's say I have a chat like this:

- message 1
- message 2
- message 3
- message 4
- message 5

I am interested in having `message 3` get retried with a different model.  What is the UX?  I tweak the params and click "Retry" and then it sends `[message 1, message 2, message 3]` to the new model (i.e., ignores 4 and 5) and then replaces the text in `message 3` when it comes back?  Or does this delete message 3 and create a new message in its place?

**Comment by tarasglek** [comment]
oooh..if we integrate it into the menu, then it will be really slick..just add a "retry-with" menu that opens up to submenu of all available models

**Comment by humphd** [comment]
How about my other question though: what does retrying an arbitrary message in a chat mean in terms of the context you send?

**Comment by tarasglek** [comment]
tabbed messages is an interesting concept

**Comment by niallo** [comment]
Threads might be interesting too. I was thinking tabs because I like how OpenAI does it (although these aren't really functional after the first message - but maybe it would work?). I haven't fully considered all the implications tho.

<img width="645" alt="Screen Shot 2023-06-07 at 10 18 51 AM" src="https://github.com/tarasglek/chatcraft.org/assets/218162/4070fe28-95f5-401f-b425-1514f8675e67">

**Comment by tarasglek** [comment]
i'd be ok with this too

**Comment by humphd** [comment]
In addition, see/test https://github.com/tarasglek/chatcraft.org/pull/98, which adds in support for initially sending with a given model without needing to dig into settings.

I'll think on the ideas in https://github.com/tarasglek/chatcraft.org/issues/59#issuecomment-1581067673, thanks for adding them.

**Comment by humphd** [comment]
This has landed.
