### ISSUE TITLE
line-buffered Incremental rendering of mermaids

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#60]
It might be possible to render them incrementally. Seems that mermaids output by gpt are always self-contained line by line. Furthermore there might be some mermaid lib that can parse the code to validate that it's correct.

**Comment by humphd** [comment]
The code I just landed has a way to validate:

https://github.com/tarasglek/chatcraft.org/blob/main/src/components/MermaidPreview.tsx#LL38C1-L49C10

You could experiment with this, but I think it might be hard to deal with the case where a diagram is actually wrong and will never re-render correctly.  In my testing, GPT often gives bogus diagram code.

**Comment by tarasglek** [comment]
This is just an idea to file for later. I like your code to figuring out errors...makes me a want a "fix errors" button

**Comment by humphd** [comment]
We render them as they stream in now, closing.
