### ISSUE TITLE
Make token-tracking work more like a receipt

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#61]
This is related to https://github.com/tarasglek/chatcraft.org/issues/59 should make token-tracking function more like a receipt that tells you how much it cost to generate the message near the model details.

This will be more useful once we add claude. 

Furthermore current token-tracking is misleading:
* it's undercounting as it simplify reflects cost if all currently visible messages were produced by gpt. Instead it should be updated every time we get a response back and stored in local storage.
* It's overcounting gpt-4 price by not differentiating different input/output costs

**Comment by tarasglek** [comment]
Found this code to track token usage. This is also the key to tracing langchain agents. https://github.com/hwchase17/langchainjs/issues/1079#issuecomment-1532315417

**Comment by humphd** [comment]
Started to look into this, but ran into https://github.com/hwchase17/langchainjs/issues/1682
