### ISSUE TITLE
TTS UI is missing

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#617]
I noticed on my phone that the TTS buttons are gone.  Then I looked on desktop, and they are gone there too.  Did we remove them somehow?

cc @Amnish04

**Comment by Amnish04** [comment]
@humphd Weird, I can still see them.
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/3d6fc448-4fc5-418c-b766-c354f6a1f435)

Are you using a supported AI provider?

**Comment by humphd** [comment]
Yes, that's the problem!
