### ISSUE TITLE
Icons for Delete submenu

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#619]
<img width="541" alt="Screenshot 2024-04-28 at 6 41 52 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/bd097a40-cb89-4e29-8dd2-987b341ff841">

We should only have the trash icon on the submenu itself, not the items in the submenu.  The one on "Delete Messages Before" should get removed:

https://github.com/tarasglek/chatcraft.org/blob/65597c70b3d0e484a4400a0836e39678aff871a3/src/components/Message/MessageBase.tsx#L550

Someone new to the project that wants to get started contributing should take this.

**Comment by priyasirohi09** [comment]
Hey Can I pick this?

**Comment by priyasirohi09** [comment]
@humphd Fixed the issue Please review and lmk
