### ISSUE TITLE
Tool Use and/or Allow tracing langchain with chatcraft

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#62]
* Add notion of tool messages that are shown differently
* WebRTC for connecting to chatcraft to local dev env per https://github.com/tarasglek/chatcraft.org/pull/68
* Tracing ui for langchain:
Chatcraft could be used to experiment with langchain.js. We might need threads for this...but current state of the art is not that hard to improve upon:
https://twitter.com/marktenenholtz/status/1656657288340590600/photo/1

Would give chatcraft a new use a live repl for langchain. Pretty sure this would be useful for developing chatcraft itself

**Comment by humphd** [comment]
I'm not sure what to do with this.  @tarasglek can you refine this, based on recent changes, or close?
