### ISSUE TITLE
Margin in free provider banner

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#620]
On mobile, I notice that the close button in the free provider banner is overlapping the text:

<img width="397" alt="Screenshot 2024-04-29 at 8 50 06 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/6e33a704-b407-4793-83c4-a0bfcc7fb40f">

We should add some margin similar to how the info icon is on the left.

**Comment by priyasirohi09** [comment]
This is happening because the close button has position as absolute

**Comment by priyasirohi09** [comment]
Sure @humphd
