### ISSUE TITLE
Chatcraft hangs webpage

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#629]
This is a bugreport from twitter. I've noticed similar weird behavior where chrome seemingly freezes while streaming responses.

I found a UI bug on chatcraft. Asked: "What is apache apisix?" using the free models in auto mode. And I got a response repeating APACHE APACHE APACHE after a normal sentence. The UI bug is not the model response, but that that some JavaScript code hangs the Firefox tab, until Firefox ask to stop the JS code running there. Sorry, I didn't found any feedback option on the website.

Note, it only hangs on a saved conversation, not on a clean one, or one that repeats the same questions (two unrelated ones)

**Comment by robmv** [comment]
Sometimes  it displays the repeated APACHE words faster., it may be a Firefox redisplay issue, I switched this time to another tab and back and the words where shown at the end of the video

[Screencast from 2024-05-07 08-47-23.webm](https://github.com/tarasglek/chatcraft.org/assets/1652983/e5e92d21-aaf0-4046-8ff2-967cdd7d7404)

The stack trace after Firefox ask for the script being stopped is:

```
Script terminated by timeout at:
oR@https://chatcraft.org/assets/index-Dl5d8yCF.js:603:53627
yFe@https://chatcraft.org/assets/index-Dl5d8yCF.js:603:55638
Bze@https://chatcraft.org/assets/index-Dl5d8yCF.js:609:8007
Fze@https://chatcraft.org/assets/index-Dl5d8yCF.js:609:8441
Pze/e.prototype.sweep@https://chatcraft.org/assets/index-Dl5d8yCF.js:609:5822
l5t@https://chatcraft.org/assets/index-Dl5d8yCF.js:1073:63873
compute/<@https://chatcraft.org/assets/index-Dl5d8yCF.js:603:8626
compute@https://chatcraft.org/assets/index-Dl5d8yCF.js:603:8582
Pt@https://chatcraft.org/assets/index-Dl5d8yCF.js:603:15281
cR@https://chatcraft.org/assets/index-Dl5d8yCF.js:613:1225
onData@https://chatcraft.org/assets/index-Dl5d8yCF.js:1073:127315
O@https://chatcraft.org/assets/index-Dl5d8yCF.js:586:327
lae/V<@https://chatcraft.org/assets/index-Dl5d8yCF.js:586:995
```

**Comment by humphd** [comment]
@robmv I can't reproduce (yet).  Do you see this in Chrome as well?

**Comment by tarasglek** [comment]
it's rate limited for long responses :)

but you should be able to do a synthetic custom provider that generate similar messages

**Comment by tarasglek** [comment]
This seems to be an issue with us incrementally updating too much, which causes markdown to get reparsed-rerendered. 
<img width="686" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/3cb9af98-ab3e-4686-a466-c10e82004c2e"> from a similar situation. We should add some throttling to incremental updates

**Comment by robmv** [comment]
Not sure if the fix is already deployed on the website, but I think it is better now. The long example URL was streamed to the page, you can see the URL growing without the browser struggling to process that. the Apache question got the response fast, without hanging and repeating APACHE.

I will test tomorrow on the low bandwidth connection I tested previously, just to be careful it isn't because I an currently on a fast one.

**Comment by humphd** [comment]
Yeah the fix @tarasglek wrote is live.  Glad you're seeing improvements!
