### ISSUE TITLE
share broken on mobile

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#634]
clicking share does nothing for me on ios whether im logged in or not

**Comment by humphd** [comment]
I was testing Sharing today, and what I think is happening is that the new native share stuff is not doing what people expect.

I used it on my Chrome browser today and was surprised.  When you click Share, it uploads the chat to the server and gets back a URL, then opens the browser's native sharing dialog vs. ours and you can pick an app. I was then able to "share" this with my Mail app and get this link:

https://99742b23.console-overthinker-dev.pages.dev/api/share/chatcraft_dev/upbueYzuwap6MlQ_Febvx

And that works.  But this isn't ideal, especially on Desktop.  On mobile it might be OK?  But really, I just want to get the link to the thing I share.

**Comment by humphd** [comment]
I just updated sharing, this is now working again.
