### ISSUE TITLE
Scroll models, but not providers in Ask menu

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#641]
We have 2 things in the Ask menu:

- models for the chosen provider
- providers

The models list can be really long (OpenRouter.ai), and it needs to overflow.  However, right now, we also scroll the providers out of sight:

<img width="352" alt="Screenshot 2024-05-20 at 5 45 52 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/30115d40-10a2-4d55-8938-2a55828b2113">

It would be nice if we didn't scroll the providers away, and only scrolled the models.  The Search at the top should probably also stay anchored.

**Comment by tarasglek** [comment]
We could probably just swap positions ...
```
- providers
  * openai
  * openrouter
- [search]
 * model 1
 * gpt-4o
 ```
