### ISSUE TITLE
Chatcraft refuses to show me completion

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#656]
<img width="834" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/7bab1a15-e3d8-4819-8e39-c8fd4baa8071">

using gpt-4o, it always clips the response under [show more] block..but i can't expand it. Weirdest bug I've seen so far

https://chatcraft.org/api/share/tarasglek/ffrwu1e_MacPyWd38itEe

**Comment by Amnish04** [comment]
@tarasglek Visited your link and don't see any assistant messages. Can't reproduce on my side either
https://chatcraft.org/api/share/Amnish04/xV24MK0UydzHkB2jYvw-h
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/41f57143-cf98-461d-9b06-c156e51ebcd2">

**Comment by tarasglek** [comment]
will try to repro and reopen
