### ISSUE TITLE
Connection error with OpenRouter

### ISSUE THREAD

**Issue by alexisargyris** [tarasglek/chatcraft.org#657]
Hello,

Yesterday I tried to switch to OpenRouterAI and got this error message:

> Error Connecting to AI Provider. error querying models API: Connection error

Can somebody please explain what this means and what to do about it? I've been using Chatcraft (+OpenAI) for many months now with zero problems. Also, there doesn't seem to be a problem at the OpenRouter side of things since I can use the playground normally.

Thanks in advance

**Comment by humphd** [comment]
I can't reproduce it:

<img width="1350" alt="Screenshot 2024-06-26 at 8 05 58 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/7df8fcc9-e379-48ef-8370-ccb726ed963d">

I wonder if it was a temporary network issue on their end?  Does it persist for you today?

**Comment by tarasglek** [comment]
@alexisargyris would be helpful to see network trace like @humphd showed

**Comment by alexisargyris** [comment]
Thanks a lot for the quick reply. I am behind a company firewall. Chatcraft + OpenAI never had any problems with that. Chatcraft + OpenRouterAI apparently is blocked. Here is what happens:

![Screenshot 2024-06-26 153745](https://github.com/tarasglek/chatcraft.org/assets/1640855/42ca673e-612c-44b0-8ae0-e994172d097a)

Maybe some port is required? Can this be avoided?

**Comment by humphd** [comment]
That's really odd, since I get the proper CORS header (`access-control-allow-origin: *`) when I hit it from here:

```sh
$ curl -I https://openrouter.ai/api/v1/models
HTTP/2 200
date: Wed, 26 Jun 2024 15:26:12 GMT
access-control-allow-credentials: true
access-control-allow-headers: Authorization, User-Agent, X-Api-Key, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, HTTP-Referer, X-Windowai-Title, X-Openrouter-Title, X-Title, X-Stainless-Lang, X-Stainless-Package-Version, X-Stainless-OS, X-Stainless-Arch, X-Stainless-Runtime, X-Stainless-Runtime-Version
access-control-allow-methods: GET,OPTIONS,PATCH,DELETE,POST,PUT
access-control-allow-origin: *
cache-control: public, max-age=0, must-revalidate
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://clerk.openrouter.ai https://cunning-heron-18.clerk.accounts.dev https://challenges.cloudflare.com https://checkout.stripe.com https://connect-js.stripe.com https://js.stripe.com https://maps.googleapis.com https://www.googletagmanager.com https://*.ingest.sentry.io; connect-src 'self' https://clerk.openrouter.ai https://cunning-heron-18.clerk.accounts.dev https://checkout.stripe.com https://api.stripe.com https://maps.googleapis.com *.google-analytics.com https://www.googletagmanager.com https://raw.githubusercontent.com https://*.ingest.sentry.io; frame-src 'self' https://challenges.cloudflare.com https://checkout.stripe.com https://connect-js.stripe.com https://js.stripe.com https://hooks.stripe.com https://us5.datadoghq.com https://*.ingest.sentry.io; img-src 'self' data: blob: https://img.clerk.com https://*.stripe.com https://www.googletagmanager.com https://t0.gstatic.com; worker-src 'self' blob:; style-src 'self' 'unsafe-inline' sha256-0hAheEzaMe6uXIKV4EehS9pu1am1lj/KnnzrOYqckXk=; upgrade-insecure-requests
strict-transport-security: max-age=63072000
x-matched-path: /api/v1/models
x-vercel-cache: MISS
x-vercel-id: cle1::d84w5-1719415571719-b6963067ed37
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 899e36db0890ac84-YYZ
```

I also notice in that errors above that it looks like you're getting some other response, maybe an HTML page from CloudFlare with that `403 Forbidden` failure?  Maybe your network is being blocked by CloudFlare somehow, or something else between you and them (your network) is injecting an error page that doesn't have the CORS headers and 403s?

**Comment by alexisargyris** [comment]
So, today I made the following test:

* Attempted to use Chatcraft with OpenRouter while being behind the company firewall. Result: failure (as above, with the same set of responses).
* Temporarily, bypassed the company firewall. Chatcraft connected to OpenRouter and everything worked as expected. Made a test query to Claude-Sonnet. Everything ok.
* Switched back to the company network. Immediately, I got a connection error.
* Set Chatcraft to use OpenAI instead of OpenRouter and made a test query. Everything ok again.

If Chatcraft is not attempting to use some blocked port while attempting to connect to OpenRouter then the reason must be the range of IP address

**Comment by humphd** [comment]
@alexisargyris try opening https://openrouter.ai/api/v1/models in your browser and see what you actually get back.  I bet it's an HTML page with error info vs. the expected JSON response (e.g., something is redirecting you).

There's no port blocking happening here.

**Comment by alexisargyris** [comment]
Yes, you are right. I get a notification about the address being blocked by the web safety filter. I'll see what can be done internally...

**Comment by alexisargyris** [comment]
Fixed at our end, thanks a lot
