### ISSUE TITLE
API Key for "default free AI Provider" is invalid 

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#668]
<img width="535" alt="Screenshot 2024-08-26 at 8 51 16 AM" src="https://github.com/user-attachments/assets/ce0f13b3-3088-41a6-a517-e2862a3afb5d">

@tarasglek is this intended?  If so, we shouldn't include a so-called "free" provider.  If not, we should fix.

**Comment by tarasglek** [comment]
Sorry about that, deleted the wrong key in groq
