### ISSUE TITLE
Free Provider Gemini-* models don't work

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#673]
@tarasglek I get 500s (nothing in the response I can debug) when I try to use the Gemini models via the Free Provider:

<img width="1342" alt="Screenshot 2024-09-01 at 5 15 44 PM" src="https://github.com/user-attachments/assets/4b3eb731-2d4a-4189-b333-37e874eafb21">

**Comment by tarasglek** [comment]
it's working for me atm. Our error reporting could be better here. Next time this happens open up network tools to see how the error was reported. Openrouter usually has something helpful for debugging, just too many different ways of reporting the error
