### ISSUE TITLE
Use better icons for llama, Gemini, and other models

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#675]
We have some code to pick a default icon for various models, see https://github.com/tarasglek/chatcraft.org/blob/2e64240f4176008b239807cdb2b12c8325487da8/src/lib/ChatCraftModel.ts#L27

Let's update it to add some of the more recent models from Facebook (llama https://llama.meta.com/), Gemini, etc. from Google, Mixtral, phi, etc.

**Comment by hpatel292-seneca** [comment]
Hi @humphd, Could I work on this issue? If so, could you please add the Hacktoberfest label so it counts towards my Hacktoberfest PR?

**Comment by humphd** [comment]
@hpatel292-seneca go for it.  There might be other models to consider besides what I listed.

**Comment by hpatel292-seneca** [comment]
@humphd are this looks good?
![image](https://github.com/user-attachments/assets/4d655c64-c9c5-4b0e-8829-8f08b39e1ae9)
![image](https://github.com/user-attachments/assets/63394a4b-ba9c-4810-93c7-033a703e743c)
![image](https://github.com/user-attachments/assets/b959c7c6-844e-4f73-aa5e-126fdbac8c44)
![image](https://github.com/user-attachments/assets/a6da79bc-f438-4560-a4d8-1ccafdafb106)

**Comment by humphd** [comment]
Is the green for llama part of the icon, or something we're doing?  It looks odd with the blue.

I love the rest

**Comment by hpatel292-seneca** [comment]
So the images I added are logos without any background, so the background color is added by some other code.

**Comment by humphd** [comment]
So the icon must be using an alpha channel, and we're bleeding the green through?  Let's fix that.  Can you use something that isn't transparent?

**Comment by hpatel292-seneca** [comment]
Here it is, I used logo with backgound
![image](https://github.com/user-attachments/assets/14aab6ce-2d7c-493c-a3e0-b585e75e93ef)

**Comment by humphd** [comment]
Yeah, that's great.  Make sure all of them are like this.  Make a PR!

**Comment by hpatel292-seneca** [comment]
Got it. Thanks

**Comment by humphd** [comment]
@hpatel292-seneca when you do PRs, always use "Fixes #675" in the description, so it auto-closes the issue too when it gets merged.
