### ISSUE TITLE
chatcraft markdown flavor does not render html tables inline

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#676]
Eg github:
<table>
  <tr>
    <th>Header 1</th>
    <th>Header 2</th>
  </tr>
  <tr>
    <td>Cell 1</td>
    <td>Cell 2</td>
  </tr>
  <tr>
    <td>Cell 3</td>
    <td>Cell 4</td>
  </tr>
</table>

chatcraft: https://chatcraft.org/api/share/tarasglek/GxuXL3M6XgAs1XJ0IlMkP

![image](https://github.com/user-attachments/assets/ca6a1f28-2fbe-42c5-8946-a4f1f775b5da)

**Comment by humphd** [comment]
It didn't use a fenced code block for HTML, I'm not sure that we should try to render everything you type.  It will make discussing HTML impossible:

<img width="916" alt="Screenshot 2024-09-05 at 4 52 02 PM" src="https://github.com/user-attachments/assets/f7faff9f-337c-431c-8092-7e11f8ab74c0">

**Comment by tarasglek** [comment]
Technically markdown supports embedded html, so we should have a way to render it. In this case, I stumbled upon this problem when trying render data in mdown tables and those failing. Getting llm to output correct html tables is easier.

 html preview is a big heavy-weight cos it display source and resulting table

**Comment by tarasglek** [comment]
Discussion html will still be possible via 
```
<html> goes into code blocks
````
