### ISSUE TITLE
[Regression] Can't paste images into chat

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#683]
Didn't we used to support pasting images in to the chat?  I can't seem to make it work.

I wonder if it's being blocked on the model I'm using, and our "vision" implementation not being smart enough to know that this is allowed?

**Comment by rjwignar** [comment]
![ChatCraftPasteTest](https://github.com/user-attachments/assets/fd615d73-a8bb-4008-b598-2357d2b57798)

I'm able to paste images into the Chat using Control+V and Windows+V to select an image from my clipboard.
This is with my OpenAI API Key stored and with gpt-4o-latest already selected, using Microsoft Edge on Windows 10.

**Comment by Amnish04** [comment]
> I wonder if it's being blocked on the model I'm using, and our "vision" implementation not being smart enough to know that this is allowed?

Yes, this happens to me when using a non-supported model.
<img width="796" alt="image" src="https://github.com/user-attachments/assets/29485fbb-7f97-4150-8e7b-2b09b1f061ff">

**Comment by humphd** [comment]
I'm hitting something else.  If I copy something on my Mac and try to paste, it seems to work.  If I try to copy an image form MS Teams, it won't paste anything.  I wonder if the way the clipboard data is shared is different...

**Comment by humphd** [comment]
Looks like Teams is a POS https://answers.microsoft.com/en-us/msteams/forum/all/teams-copy-image-not-working/dfa225ca-3466-49b8-b41a-f2f31c2b140f

I think we're OK.
