### ISSUE TITLE
chatcraft CI broke chatcraft

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#686]
Preview link in https://github.com/tarasglek/chatcraft.org/pull/684 worked fine...but after I merged it. No cloudflare builds work anymore.

Dexie seems upset, not sure if it's the problem: 
![image](https://github.com/user-attachments/assets/6b20a6f2-c0db-4419-aa61-013b00482f2e)

**Comment by humphd** [comment]
I did a redeploy and have a slightly different error:

```
index-Dwl0pF1t.js:643 Unable to update OpenAI models, using defaults. Error: error querying models API: DBe is not a function
    at hy.queryModels (index-Dwl0pF1t.js:575:2080)
    at async index-Dwl0pF1t.js:643:6166
```

That DBe bit looks like it's in React.

Can't reproduce this locally.  Build logs in Cloudflare looked good.  I can't debug more til tonight :( (@Amnish04, any thoughts?)

**Comment by humphd** [comment]
In an incognito window, prod is working for me (no providers).  So I'd say one of our providers is suddenly sending crappy model data to us or something is failing when we try to get the models, and it's crashing.

**Comment by tarasglek** [comment]
how are you getting the sane backtrace? I can't do anything with these minified craps

**Comment by humphd** [comment]
The bug here is that the `pnpm` lock file version got updated, and CloudFlare's default install of `pnpm` is v8 vs. v9.  As a result, it ignored the lockfile, deeming it incompatible, which led to broken deps.

I've told the build environments in CloudFlare to install version 9, and now it's fine.
