### ISSUE TITLE
Fix icon for Meta-Llama-3.1-405B-Instruct

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#704]
<img width="347" alt="Screenshot 2024-10-28 at 5 24 45 PM" src="https://github.com/user-attachments/assets/7f4aca47-4e1d-4d7e-ad6d-902a7299c0f2">

**Comment by gitdevjin** [comment]
Hello, @humphd.
I opened a [PR](https://github.com/tarasglek/chatcraft.org/pull/712) for this issue.

**Comment by humphd** [comment]
When you make your PR, put `Fixes #704` in the description of the PR so it auto-closes the issue.

**Comment by gitdevjin** [comment]
@humphd Thank you for the tip! I think I learned it in our course, but I think I forgot 😭
