### ISSUE TITLE
Sometime AI message retry is failing.

### ISSUE THREAD

**Issue by hpatel292-seneca** [tarasglek/chatcraft.org#716]
https://github.com/user-attachments/assets/769179fd-2428-4725-8ec9-3fe759ea887e

Hi @humphd @tarasglek , I notice that some AI message retry is failing API call.

**Comment by humphd** [comment]
What's the actual error Gemini is returning?  Your video doesn't show it

**Comment by tarasglek** [comment]
It's some 429 or something from openrouter... can repro this by using some free model that's rate-limited

**Comment by humphd** [comment]
Let's catch this case (error) and show an error message with our `useAlert()` hook and `error()`.

**Comment by hpatel292-seneca** [comment]
I can work on it.

**Comment by humphd** [comment]
@hpatel292-seneca awesome, thank you
