### ISSUE TITLE
UI for sharing, settings

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#72]
In order to get the "sharing" stuff in, I need to rework the UI.  While I'm doing it, I'm also trying to think about other things that need to get added/moved.  Here's a concept:

<img width="981" alt="Screenshot 2023-05-19 at 3 32 57 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/9f5a5c99-2725-4ce1-8bd2-9da189a9d90b">

In this updated UI, notice a few things:

1. I'm logged in (upper-right), showing my GitHub avatar vs. the stock one.  If I'm not logged in, it would show a generic avatar.
2. The icon to Expand the chat has been moved to the left-hand side.  On the right-hand side, 2 new buttons are added: 1) Settings; 2) Share.  Both can expose more UI to the user.  With Settings, we'd show various options to control the model, etc. and with Share we'd let you Copy, Download, or post and Share a chat.  These could either be a modal, or we could slide-up a panel that's attached to the prompt form, then slide it away again.

Another question: how important is the "Single Message Mode" checkbox?  Could it get moved into Settings?

Thoughts?

**Comment by steven4354** [comment]
@humphd just speaking purely from my usage so might not fit everyone, but here's my thoughts

- ive never use the single message mode, i find i almost always need to do 2-3 msgs in most convos and some expand into 5-7 msgs or mor
- the share is super helpful or some way to copy the entire chat, what i really want is to be able to copy my migrations/backend on 2-3 messages and then plop that back into a new convo and not needing to do it 1 by 1 using the current copy per message

hope that might be helpful! happy to dig further into any item

**Comment by tarasglek** [comment]
single message mode would be super painful in settings, i already find switching gpt/chatgpt painful. I think if we had a quick settings menu to toggle large textbox, gpt model, single-msg mode, it would be ok.
Though I think I would like to just have 2-click (one to open and one to select) access to all options...less clicks would be even better, if options magically popped up :)

**Comment by tarasglek** [comment]
I have a crazy idea. Why not have everything render as a chat message to avoid modal dialogs.

Eg current input dialog could render inline with all the chats..and one would scroll up away from it when looking at history.

We could then specify openai options chakra [accordion](https://chakra-ui.com/docs/components/accordion/usage) under it...similarly once we get responses from openai, we could put read-only copy of dialog into accordions/burgers attached to those messages.

This would also get rid of weird chat-prompt input for entering openai key..we'd just show the existing dialog inline for that..just hide all the other options in it until key is entered & validated.

**Comment by tarasglek** [comment]
I just realized that inline chatbox is exactly how one would implement threads

**Comment by humphd** [comment]
@tarasglek can you expand on your ideas a bit, I don't totally follow everything you're saying.

So put the "prompt" inline as another message.  I get that, it's basically what GitHub does:

<img width="705" alt="Screenshot 2023-05-21 at 9 02 58 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/a1518314-0790-4877-abf1-ec03e1b0fd4c">

But what are you talking about with threads and tracing?  Can you take a crack at describing the entire UI you imagine?

**Comment by tarasglek** [comment]
<img width="683" alt="image" src="https://github.com/tarasglek/chatcraft.org/assets/857083/55cbf0f4-216c-4d0a-9a08-936e085a20f5">
Does this make sense?

**Comment by tarasglek** [comment]
Regarding langchain, we can use thread-indentation to show tool use.

**Comment by tarasglek** [comment]
It might be a giant distraction
