### ISSUE TITLE
Text-to-Speech button is redudant in Mobile view.

### ISSUE THREAD

**Issue by hpatel292-seneca** [tarasglek/chatcraft.org#746]
![image](https://github.com/user-attachments/assets/460ee678-7a7f-434a-9fb6-69daf7261970)

**Comment by hpatel292-seneca** [comment]
Hi @tarasglek, if you want to make this change, I can work on it.

**Comment by hpatel292-seneca** [comment]
I am not sure. I notice it while working on a PR https://github.com/tarasglek/chatcraft.org/pull/730.
In current code, https://github.com/tarasglek/chatcraft.org/blob/09dd743cfcb81126c6370041577be77164508539/src/components/PromptForm/PromptSendButton.tsx#L398

the PromptSendButton has different logic for mobile and desktop views. However, the mobile view logic contains redundant code for text-to-speech functionality.

In my PR, I didn’t change the existing logic. I simply refactored the menu logic by extracting it into a common component and replaced the Chakra UI menu with custom menu components.

**Comment by Amnish04** [comment]
I think the issue here is that we have a TTS toggle button both inside the button group and the model selection menu. We might have moved this option inside the menu to save real estate on mobile, but forgot to delete from the button group?

**Comment by humphd** [comment]
Ah.  Yes, let's not duplicate.  The space on mobile is so small, we need it all.
