### ISSUE TITLE
Lag, can't delete user input

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#75]
1. This commit seems to have introduced a lot of lag...often can't type into chatbox now.
2. Lost delete button on user messages
https://github.com/tarasglek/chatcraft.org/commit/c052184d80618020c52c47bebd454c2b33982bc3

Looking at the code I don't understand why things got expensive. I noticed we now rerender mermaid diagram on every character too. Perhaps we need some test for overly frequent state updates? Is there some standard react tooling to help with that?

**Comment by humphd** [comment]
Can you give STR for lag?

I think rendering previews as tokens stream in is always going to be bad UX: poor performance as Mermaid/HTML get re-rendered; high failure rate as syntax is incomplete, etc.  I'd prefer to only render when message is complete.

Can you split this into two different issues, they don't seem related.  Also, you say "Lost delete button," but it got moved into the dots-menu (like GitHub).  No good?

**Comment by tarasglek** [comment]
i'm no longer seeing either issue. will open separate issues if i repro
