### ISSUE TITLE
New Conversation button

### ISSUE THREAD

**Issue by tarasglek** [tarasglek/chatcraft.org#77]
Nobody knows what fork means. We should have a "New Chat" button that's actually a menu, that has "Blank Chat" and "Duplicate Chat" and both open new windows.

**Comment by humphd** [comment]
Do something like GitHub does with default actions, which you can override?

<img width="320" alt="Screenshot 2023-06-01 at 10 13 41 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/1cb0d391-8464-405b-95bc-7c7ed9e504fe">

**Comment by tarasglek** [comment]
i would prefer to not have a single click do anything, 1 click on new chat, second click on whether you want blank or duplicate chat...https://chakra-ui.com/docs/components/menu is what i'm visualizing
