### ISSUE TITLE
Let's try to define and prototype tools

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#86]
We've spoken a lot about "tools," and the abilities they'd unlock.  Now that we have the message types in place, routing, and the db backend, I think we have most of the pieces necessary to start playing around with this.

It likely makes sense to consider this in the context of Langchain, which already gives us access to [Agents](https://js.langchain.com/docs/modules/agents/) and [Tools](https://js.langchain.com/docs/modules/agents/tools/).  Here, a "tool" means:

```ts
interface Tool {
  call(arg: string): Promise<string>;
  name: string;
  description: string;
}
```

So we could begin by providing a way to write/upload/store JS (or TS and transpile, or I guess whatever lang and compile to WASM) which exports a `call(arg: string): Promise<string>` function.

We now have `/c/*` for chats.  What about `/t/*` for tools?

How do we use these tools?  Do we create a [Toolkit](https://js.langchain.com/docs/modules/agents/toolkits/) for an agent to use, based on all the `/t/*` tools owned by the user?  Or do we have some way to insert a Tool as context in a message?  Or both?

**Comment by humphd** [comment]
[OpenAI announced](https://openai.com/blog/function-calling-and-other-api-updates) changes to how models interact with functions:

> Function calling
>
> Developers can now describe functions to gpt-4-0613 and gpt-3.5-turbo-0613, and have the model intelligently choose to output a JSON object containing arguments to call those functions. This is a new way to more reliably connect GPT's capabilities with external tools and APIs.
>
>These models have been fine-tuned to both detect when a function needs to be called (depending on the user’s input) and to respond with JSON that adheres to the function signature. Function calling allows developers to more reliably get structured data back from the model. For example, developers can:
>
>Create chatbots that answer questions by calling external tools (e.g., like ChatGPT Plugins)
>
Convert queries such as “Email Anya to see if she wants to get coffee next Friday” to a function call like send_email(to: string, body: string), or “What’s the weather like in Boston?” to get_current_weather(location: string, unit: 'celsius' | 'fahrenheit').
>
>Convert natural language into API calls or database queries
>
>Convert “Who are my top ten customers this month?” to an internal API call such as get_customers_by_revenue(start_date: string, end_date: string, limit: int), or “How many orders did Acme, Inc. place last month?” to a SQL query using sql_query(query: string).
>
>Extract structured data from text
>
>Define a function called extract_people_data(people: [{name: string, birthday: string, location: string}]), to extract all people mentioned in a Wikipedia article.
>
>These use cases are enabled by new API parameters in our /v1/chat/completions endpoint, functions and function_call, that allow developers to describe functions to the model via JSON Schema, and optionally ask it to call a specific function. Get started with our [developer documentation](https://platform.openai.com/docs/guides/gpt/function-calling) and [add evals](https://github.com/openai/evals) if you find cases where function calling could be improved

This would make it pretty easy to host tools in ChatCraft that can be easily invoked by the model.

**Comment by humphd** [comment]
Developer docs for Function Calling are [here](https://platform.openai.com/docs/guides/gpt/function-calling).

**Comment by humphd** [comment]
OpenAI Cookbook Example of Function Calling [here](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_Chat_models.ipynb)

**Comment by tarasglek** [comment]
Note openai functions add a function message type.

https://platform.openai.com/docs/api-reference/chat/create

**Comment by tarasglek** [comment]
Langchain.js function call stuff: https://github.com/hwchase17/langchainjs/blob/53b6cb4fd9365e26b21c5e40ed2ddd8077562fdb/langchain/src/chat_models/openai.ts#L87

**Comment by tarasglek** [comment]
So I think there is only one way to do this.

1) Add a second "system message" where we can edit schema for openai functions. These will likely be catalog of built-in functions showCode(code, language), someDBOperations and user-defined functions like "runSQL". Flag to force functions to run, "just show me the code" becomes a forced "renderCode" call

2) When model tells us to run code by sending us a reply with "assistant" messages with "content":null and "function_call", we render function call similar to how we do now...have per-function-call auto-run(eg renderCode is harmless)

3) if auto-run is specific, we immediately pipe results back..if not, we have option of running the function and sending results back optionally(this is useful when using model to generate sql queries and no further interaction is needed), same thing happens if we have a function to apply cloudformation, etc

**Comment by humphd** [comment]
Let me think out-loud, based on what you wrote above.

First, a tool or function (I think "function" is probably closer to my concept of what this is) has the following:

1. name
2. description
3. input arg schema (JSON Schema)
4. implementation in JS

A bunch of this is based on https://github.com/openai/openai-node/blob/dc821be3018c832650e21285bade265099f99efb/api.ts#L26-L50 and https://platform.openai.com/docs/api-reference/chat/create#chat/create-functions, but we can also colocate the implementation, since we'll run these functions in the browser.

Here's an example:

```js
{
  name: "echo",
  description: "echoes the input back",
  parameters: {
    type: "object",
    properties: {
      value: {
        type: "string",
        description: "The value to echo back",
      },
      required: ["value"]
    }
  },
  code: "function(value) {\n return value;\n }"
}
```

We can put these functions in a new table in the database.  This lets us re-use them across different chats, and refer to them by `id` or something within a chat vs. having them live there.  A shared chat could embed them so you can pass them around.

In terms of the UI for working with them, we could either do it all in the current message view, or we could introduce a new view.  I think I'd do the latter.  For example:

- add a new section in the left-hand sidebar for "Functions" (i.e., you have your Chats, Shared Chats, and Functions).
- you can "open" or "edit" a function, which would display a card with the name, description, schema, and an editor for working on the code
- in a typical chat, you can "include" these functions, maybe in the system prompt (e.g., add some UI for choosing them) and they show-up by name (i.e., don't show the whole function, but clicking on it takes you to the other view where you can read/edit).
- The system prompt could also have an "Add Function..." button or something that takes you to the function editor
- If you select functions in your system prompt, we tell the model to use these, and can perhaps have some UI way to force the use of them vs. "auto" where it chooses.

This isn't the right UI, but imagine having a way to easily add/remove functions by name in the system prompt message, and also to go write a new one:

<img width="915" alt="Screenshot 2023-07-11 at 11 03 32 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/c1ce291e-ad16-4157-b52c-0bb24f9ce922">

**Comment by tarasglek** [comment]
> 1. name
> 2. description
> 3. input arg schema (JSON Schema)
> 4. implementation in JS

I slept on this. I think a tool is gonna be something like  [JS module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) + typescript type annotations for it. We can use typescript tooling to convert mapping into json-schema that openai requires

So a tool would be a http://-loadable JS module with some metadata describing what's in it. While at it, we can also include a system prompt in that metadata bundle.

**Comment by tarasglek** [comment]
I was thinking 
```typescript
/**
echoes the input back
@param value The value to echo back
*/
export function echo(value: string) {
  return value;
}
```
I would like to be able to include multiple functions per module this way...but your way is much easier to implement

We could combine system prompts when multiple modules are used

**Comment by humphd** [comment]
I think making single-function modules is more in the spirit of the APIs, where you provide an array of functions to use.  I agree that you'll want multiple functions in lots of cases, but being able to compose them together would be more flexible.  I also think that separating functions from one another, and also from the chat/messages, makes them more reusable.

In the UI we could have a way to get GPT to generate the structured bits (name, params, etc) based on the code you write.  However, we could provide a way to enter them manually.

So can we get practical?

1. What's our naming here, is it "Tool" or "Function"?
2. Add db table to store them (metadata + blob for code)
3. Add routing to be able to access them and load dynamically via URL
4. Some initial UI for writing/editing

Once those are in place, we can work on integration UI into current chat, system prompt, etc.

**Comment by tarasglek** [comment]
1. To me Tool is combination of interaction(eg fetch call to clickhouse) and formatting function(eg render as graph or markdown) and system prompt to direct chatcraft to use it
2. db is a followup to me.. if we can load module payloads, we list em in a blog for now..somewhere outside of chatcraft
3. same opinion as ^
4. again, i'd be ok with editing the tool outside of chatcraft for MVP

**Comment by humphd** [comment]
So are you imagining this more like an "App Store" where these functions are vetted and stored centrally somewhere outside of ChatCraft?  I was imagining us doing this without a central store, but I can see the value of both ways.  This is why figuring out the db/routing/loading first was important to me, since we need them to have a home in your existing data.

**Comment by tarasglek** [comment]
I'm imagining it as programming lego. toolbox/appstore is nice but not required to use tools.

**Comment by humphd** [comment]
I'm going to continue to push to have this become more concrete so I can start coding.

"Programming Lego" is nice, and to me it implies the idea of individual, atomic, building blocks.  So my proposal is:

1. Functions are code + metadata we store locally in the db (lego).  They are ES Modules that we can load on demand at runtime from db via Blob URL and invoke (i.e., they live outside the app bundle).
2. System Prompts can include one or more functions (e.g., by name), but they aren't "stored" there.  Including functions in a prompt means the LLM may ask us to call them in the response.
3. A Tool is the combo of a system prompt + functions I can use to do something, so essentially: a chat with custom system prompt and included functions.

I think the above would be enough to build a prototype to try, and then we can figure out editing, sharing, etc.

Sound good?  What did I get wrong here?

**Comment by tarasglek** [comment]
2,3 are good. But confused as to what "store locally in the db" means

**Comment by humphd** [comment]
I mean we can store the actual function code in the db as either a `string` or `Blob` and then when we want to use it at runtime, we can.

```js
// Get a function from the db
const fn = await db.functions.get(id);
// Grab it's "code" which is a blob of the JS ES Module with type text/javascript
const blob = record.code;
// Use that Blob to create a dynamic URL
const url = URL.createObjectURL(blob);
// Load the module at runtime and grab the function we want to use
const { myFunction } = await import(url);
// Call the function
await myFunction(inputData);
```

**Comment by tarasglek** [comment]
We can do that. I think I would eventually want to import external files, but that's a bigger feature.

**Comment by tarasglek** [comment]
I'm sold on your proposal

**Comment by humphd** [comment]
Another question before I start implementing this.

In the UI for creating/editing a function, I need to know how to handle metadata for a function. What I'm imagining is that you can go to `chatcraft.org/f/new` and create a function, or `chatcraft.org/f/:id` or maybe just use the function name as id, and edit an existing.  I'm trying to decide how to do the layout for what you see when you get there.

I think we have two options:

1. A bunch of form inputs (function name, description, etc) followed by an editor view for the code.
2. Just an editor view, and all metadata is somehow extracted from the code.

Doing 1. is obviously easier from an implementation point of view.  Is there value in trying to do everything via code?  Without needing complex parsing, we could use what I suggested above and put everything into exports on the module:

```js
export const name = "echo";

export const description = "echoes the input back";

export const parameters = {
  type: "object",
  properties: {
    value: {
      type: "string",
      description: "The value to echo back",
    },
    required: ["value"],
  },
};

export default function (value: string) {
  return value;
}
```

What's nice about this is that we can validate the module to make sure it's working before we save to db.  When we save to db, we can `import()` the module and extract the metadata to put into other fields.

Which way should I go?

**Comment by tarasglek** [comment]
I vote for 2.

**Comment by humphd** [comment]
Started playing with this, and it's going to work:

<img width="1105" alt="Screenshot 2023-07-16 at 2 03 41 PM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/448b611a-c81a-4e6e-8e8c-8fc12621909e">

In the screenshot above, you can see a code editor, and I'm able to parse the module, dynamically import it, and extract the features I want (notice the name and description being used dynamically in the header).

Code to do the extraction is this:

```ts
const parseModule = async (code: string) => {
  const blob = new Blob([code], { type: "text/javascript" });
  const url = URL.createObjectURL(blob);

  try {
    return import(/* @vite-ignore */ url);
  } catch (err: any) {
    console.warn("Unable to parse module", err);
    throw new Error(`Unable to parse module: ${err.message}`);
  } finally {
    URL.revokeObjectURL(url);
  }
};
```

I'll keep playing and post a PR this week.

**Comment by tarasglek** [comment]
Microsoft released a library to do something similar to what we are doing here https://github.com/microsoft/TypeChat/tree/4d34a5005c67bc49444e6e6d016a9262cf24b38d

**Comment by humphd** [comment]
This is done!
